from undp_nuprp.reports.views.base.base_report import GenericReportView
from undp_nuprp.reports.views.base.map_report import GenericMapReportView
from undp_nuprp.reports.views.survey_stats.household_survey_stats.enumerator_household_survey_stats_view import EnumeratorHouseholdSurveyStatsView
from undp_nuprp.reports.views.survey_stats.household_survey_stats.household_survey_stats_view import HouseholdSurveyStatsView
from undp_nuprp.reports.views.dashboard.sif_crmif.base_sif_crmif_report_view import BaseSIFCRMIFReportView
from undp_nuprp.reports.views.dashboard.sif_crmif.crmif_report_view import CRMIFReportView
from undp_nuprp.reports.views.dashboard.sif_crmif.sif_report_view import SIFReportView
from undp_nuprp.reports.views.dashboard.pg_member_information_report_view import PGMemberInformationReportView
from undp_nuprp.reports.views.dashboard.community_mobilization_indicators_view import CommunitiMobilizationReportView
from undp_nuprp.reports.views.dashboard.socio_economic_fund_grant_indicators_view import SocioEconomicFundGrantReportView
from undp_nuprp.reports.views.dashboard.climate_housing_developement_fund_view import ClimateHousingDevelopmentFundView
from undp_nuprp.reports.views.dashboard.nutrition_report_view import NutritionReportView
from undp_nuprp.reports.views.dashboard.household_survey_indicators_view import HouseholdSurveyIndicatorView
from undp_nuprp.reports.views.dashboard.pg_hh_head_inforamtion_report_view import PGHHHeadInformationReportView
from undp_nuprp.reports.views.dashboard.pg_hh_information_report_view import PGHHInformationReportView
from undp_nuprp.reports.views.dashboard.urban_governance_and_planning_indicators_view import UrbanGovernanceAndPlanningReportView
from undp_nuprp.reports.views.dashboard.o_and_m_funds_view import OAndMFundsView
from undp_nuprp.reports.views.dashboard.economic_development_and_livelihood_view import EconomicDevelopmentAndLivelihoodView
from undp_nuprp.reports.views.dashboard.savings_and_credit_view import SavingsAndCreditView
from undp_nuprp.reports.views.dashboard.infrastructure_sif_and_crmif_view import InfrastructureSIFAndCRMIFView
from undp_nuprp.reports.views.dashboard.training_and_awareness_raising_view import TrainingAndAwarenessRaisingView
from undp_nuprp.reports.views.dashboard.cdc_performance_indicators_view import CDCPerformanceReportView
from undp_nuprp.reports.views.interactive_maps.interactive_map_report import GenericInteractiveMapReportView
from undp_nuprp.reports.views.interactive_maps.output_three.sef_grantees_map_report_view import SEFGranteesMapReportView
from undp_nuprp.reports.views.interactive_maps.output_three.nutrition_grantees_map_report_view import NutritionGranteesMapReportView
from undp_nuprp.reports.views.interactive_maps.output_three.violence_against_woman_committee_map_report_view import ViolenceAgainstWomanCommitteeMapReportView
from undp_nuprp.reports.views.interactive_maps.output_one.ward_prioritization_map_report_view import WardPrioritizationMapReportView
from undp_nuprp.reports.views.interactive_maps.output_one.pro_poor_and_climate_resilient_urban_strategy_map_report_view import ProPoorClimateResilientUrbanStrategyMapReportView
from undp_nuprp.reports.views.interactive_maps.output_one.poverty_condition_map_report_view import PovertyConditionMapReportView
from undp_nuprp.reports.views.interactive_maps.output_two.community_action_plan_map_report_view import CommunityActionPlanMapReportView
from undp_nuprp.reports.views.interactive_maps.output_two.mobilized_primary_group_member_map_report_view import MobilizedPrimaryGroupMemberMapReportView
from undp_nuprp.reports.views.interactive_maps.output_two.total_saving_map_report_view import TotalSavingMapReportView
from undp_nuprp.reports.views.interactive_maps.output_four.housing_development_fund_loan_map_report_view import CHDFLoanMapReportView
from undp_nuprp.reports.views.interactive_maps.output_four.low_cost_housing_unit_map_report_view import LowCostHousingUnitMapReportView
from undp_nuprp.reports.views.interactive_maps.output_five.intervention_map_report_view import InterventionMapReportView
from undp_nuprp.reports.views.interactive_maps.output_five.sif_intervention_map_report_view import SIFInterventionMapReportView
from undp_nuprp.reports.views.interactive_maps.output_five.crmif_intervention_map_report_view import CRMIFInterventionMapReportView
from undp_nuprp.reports.views.maps.survey_map_location_view import SurveyMapLocationView
from undp_nuprp.reports.views.maps.pg_member_location_view import PGMemberLocationReportView
from undp_nuprp.reports.views.maps.household_map_location_view import HouseholdMapLocationView
from undp_nuprp.reports.views.login_report_view import UserLoginReportView

__author__ = "generated by make_init"

__all__ = ['GenericReportView']
__all__ += ['GenericMapReportView']
__all__ += ['EnumeratorHouseholdSurveyStatsView']
__all__ += ['HouseholdSurveyStatsView']
__all__ += ['CRMIFReportView']
__all__ += ['SIFReportView']
__all__ += ['BaseSIFCRMIFReportView']
__all__ += ['PGMemberInformationReportView']
__all__ += ['CommunitiMobilizationReportView']
__all__ += ['SocioEconomicFundGrantReportView']
__all__ += ['ClimateHousingDevelopmentFundView']
__all__ += ['NutritionReportView']
__all__ += ['HouseholdSurveyIndicatorView']
__all__ += ['PGHHHeadInformationReportView']
__all__ += ['PGHHInformationReportView']
__all__ += ['UrbanGovernanceAndPlanningReportView']
__all__ += ['OAndMFundsView']
__all__ += ['EconomicDevelopmentAndLivelihoodView']
__all__ += ['SavingsAndCreditView']
__all__ += ['InfrastructureSIFAndCRMIFView']
__all__ += ['TrainingAndAwarenessRaisingView']
__all__ += ['CDCPerformanceReportView']
__all__ += ['SEFGranteesMapReportView']
__all__ += ['NutritionGranteesMapReportView']
__all__ += ['ViolenceAgainstWomanCommitteeMapReportView']
__all__ += ['WardPrioritizationMapReportView']
__all__ += ['ProPoorClimateResilientUrbanStrategyMapReportView']
__all__ += ['PovertyConditionMapReportView']
__all__ += ['CommunityActionPlanMapReportView']
__all__ += ['MobilizedPrimaryGroupMemberMapReportView']
__all__ += ['TotalSavingMapReportView']
__all__ += ['CHDFLoanMapReportView']
__all__ += ['LowCostHousingUnitMapReportView']
__all__ += ['SIFInterventionMapReportView']
__all__ += ['InterventionMapReportView']
__all__ += ['CRMIFInterventionMapReportView']
__all__ += ['GenericInteractiveMapReportView']
__all__ += ['SurveyMapLocationView']
__all__ += ['PGMemberLocationReportView']
__all__ += ['HouseholdMapLocationView']
__all__ += ['UserLoginReportView']
