version: "3"
   
services:
  db:
    image: postgis/postgis:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=undpnuprp
      - POSTGRES_HOST=localhost
    ports:
      - 5434:5432
  app:
    container_name: undpnuprp
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - 8001:8001
    volumes:
      - ./:/app/
    depends_on:
      - db
    env_file:
      - .env