from blackwidow.core.forms.users.account_inline_form import AccountInlineForm
from blackwidow.core.forms.common.email_address_form import EmailAddressForm
from blackwidow.core.forms.common.contact_address_form import ContactAddressForm
from blackwidow.core.forms.common.phone_number_form import PhoneNumberForm
from blackwidow.core.forms.files.fileobject_form import FileObjectForm
from blackwidow.core.forms.files.imagefileobject_form import ImageFileObjectForm
from blackwidow.core.forms.users.console_user_form import ConsoleUserForm
from blackwidow.core.forms.users.system_admin_form import SystemAdminForm
from blackwidow.core.forms.users.web_user_form import WebUserForm
from blackwidow.core.forms.users.custom_field_value_form import CustomFieldValueForm
from blackwidow.core.forms.configurabletypes.configurabletype_form_mixin import ConfigurableTypeFormMixin
from blackwidow.core.forms.stores.store_form import StoreForm
from blackwidow.core.forms.system.device_form import UserDeviceForm
from blackwidow.core.forms.organizations.form import OrganizationForm
from blackwidow.core.forms.kpi.kpi_form import PerformanceIndexForm
from blackwidow.core.forms.account.consoleuser_reset_password_form import ConsoleUserResetPasswordForm
from blackwidow.core.forms.account.logout_form import LogoutForm
from blackwidow.core.forms.account.login_form import LoginForm
from blackwidow.core.forms.account.reset_password_form import PasswordResetRequestForm
from blackwidow.core.forms.account.reset_password_form import SetPasswordForm
from blackwidow.core.forms.account.register import RegisterForm
from blackwidow.core.forms.process.approval_level import ApprovalLevelForm
from blackwidow.core.forms.process.approval_process import ApprovalProcessForm
from blackwidow.core.forms.manufacturers.manufacturer_form import ManufacturerForm
from blackwidow.core.forms.common.location_form import LocationForm
from blackwidow.core.forms.client_visit.client_visit import VisitClientForm
from blackwidow.core.forms.roles.form import RoleForm
from blackwidow.core.forms.alert_config.alert_config_form import AlertConfigForm
from blackwidow.core.forms.information.information_object_form import InformationObjectForm
from blackwidow.core.forms.information.news_form import NewsForm
from blackwidow.core.forms.information.alert_group_form import AlertGroupForm
from blackwidow.core.forms.information.alert_form import AlertForm
from blackwidow.core.forms.email_template.email_template_form import EmailTemplateForm
from blackwidow.core.forms.email_template.alert_email_template_form import AlertEmailTemplateForm
from blackwidow.core.forms.allowances.ta_submission_form import TASubmissionForm
from blackwidow.core.forms.permissions.filter_form import QueryFilterForm
from blackwidow.core.forms.permissions.form import PermissionForm
from blackwidow.core.forms.permissions.permission_assignment_form import PermissionAssignmentForm
from blackwidow.core.forms.queue.import_queue_form import ImportFileQueueForm
from blackwidow.core.forms.files.apkfileobject_form import ApplicationFileObjectForm
from blackwidow.core.forms.files.xmlfileobject_form import XMLFileObjectForm
from blackwidow.core.forms.files.importfileobject_form import ImportFileObjectForm
from blackwidow.core.forms.installation.installer_form import InstallerForm
from blackwidow.core.forms.common.bank_account_form import BankAccountForm
from blackwidow.core.forms.common.mobile_banking_form import MobileBankingForm
from blackwidow.core.forms.common.education_form import EQualificationForm
from blackwidow.core.forms.common.qr_code_form import QRCodeForm
from blackwidow.core.forms.common.domain_entity_meta_form import DomainEntityMetaForm
from blackwidow.core.forms.common.custom_field_form import CustomFieldForm
from blackwidow.core.forms.structure.warehouse_form import WareHouseForm
from blackwidow.core.forms.financial.client_financial_information_form import FinancialInformationForm
from blackwidow.core.forms.geography.geography_form import GeographyForm
from blackwidow.core.forms.geography.geography_level_form import GeographyLevelForm
from blackwidow.core.forms.clients.client_meta_form import ClientMetaForm
from blackwidow.core.forms.clients.client_form import ClientForm
from blackwidow.core.forms.clients.client_supporter_form import ClientSupporterForm
from blackwidow.core.forms.role_filters.entity_form import RoleFilterEntityForm
from blackwidow.core.forms.role_filters.form import RoleFilterForm

__author__ = "generated by make_init"

__all__ = ['AccountInlineForm']
__all__ += ['SystemAdminForm']
__all__ += ['WebUserForm']
__all__ += ['ConsoleUserForm']
__all__ += ['CustomFieldValueForm']
__all__ += ['ConfigurableTypeFormMixin']
__all__ += ['StoreForm']
__all__ += ['UserDeviceForm']
__all__ += ['OrganizationForm']
__all__ += ['PerformanceIndexForm']
__all__ += ['ConsoleUserResetPasswordForm']
__all__ += ['LogoutForm']
__all__ += ['LoginForm']
__all__ += ['PasswordResetRequestForm']
__all__ += ['SetPasswordForm']
__all__ += ['RegisterForm']
__all__ += ['ApprovalLevelForm']
__all__ += ['ApprovalProcessForm']
__all__ += ['ManufacturerForm']
__all__ += ['VisitClientForm']
__all__ += ['RoleForm']
__all__ += ['AlertConfigForm']
__all__ += ['NewsForm']
__all__ += ['AlertGroupForm']
__all__ += ['InformationObjectForm']
__all__ += ['AlertForm']
__all__ += ['EmailTemplateForm']
__all__ += ['AlertEmailTemplateForm']
__all__ += ['TASubmissionForm']
__all__ += ['QueryFilterForm']
__all__ += ['PermissionForm']
__all__ += ['PermissionAssignmentForm']
__all__ += ['ImportFileQueueForm']
__all__ += ['FileObjectForm']
__all__ += ['ImageFileObjectForm']
__all__ += ['ApplicationFileObjectForm']
__all__ += ['XMLFileObjectForm']
__all__ += ['ImportFileObjectForm']
__all__ += ['InstallerForm']
__all__ += ['LocationForm']
__all__ += ['BankAccountForm']
__all__ += ['EmailAddressForm']
__all__ += ['MobileBankingForm']
__all__ += ['EQualificationForm']
__all__ += ['PhoneNumberForm']
__all__ += ['QRCodeForm']
__all__ += ['DomainEntityMetaForm']
__all__ += ['ContactAddressForm']
__all__ += ['CustomFieldForm']
__all__ += ['WareHouseForm']
__all__ += ['FinancialInformationForm']
__all__ += ['GeographyForm']
__all__ += ['GeographyLevelForm']
__all__ += ['ClientMetaForm']
__all__ += ['ClientForm']
__all__ += ['ClientSupporterForm']
__all__ += ['RoleFilterEntityForm']
__all__ += ['RoleFilterForm']
