# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-03-16 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuprp_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputTitleLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=555)),
                ('output', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
