# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-01-31 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nuprp_admin', '0001_initial'),
        ('core', '0002_auto_20220131_1021'),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='photos',
            field=models.ManyToManyField(to='core.ImageFileObject'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='respondent_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Client'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='respondent_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.InfrastructureUnit'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.Survey'),
        ),
        migrations.AddField(
            model_name='surveyexporttaskqueue',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='surveyexporttaskqueue',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='surveyexporttaskqueue',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='surveyexporttaskqueue',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='survey.SurveyExportTaskQueue'),
        ),
        migrations.AddField(
            model_name='surveyexporttaskqueue',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='survey',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='survey',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='survey',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='survey',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='survey.Survey'),
        ),
        migrations.AddField(
            model_name='survey',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='sectionresponse',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='sectionresponse',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='sectionresponse',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='sectionresponse',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='survey.SectionResponse'),
        ),
        migrations.AddField(
            model_name='sectionresponse',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='sectionresponse',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Section'),
        ),
        migrations.AddField(
            model_name='sectionresponse',
            name='survey_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyResponse'),
        ),
        migrations.AddField(
            model_name='section',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='section',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='section',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='section',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='survey.Section'),
        ),
        migrations.AddField(
            model_name='section',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='section',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Section'),
        ),
        migrations.AddField(
            model_name='section',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Answer'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='survey.QuestionResponse'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Question'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='section_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SectionResponse'),
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='question',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='question',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='question',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='survey.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='question',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Section'),
        ),
        migrations.AddField(
            model_name='povertyindex',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='povertyindex',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='povertyindex',
            name='household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nuprp_admin.Household'),
        ),
        migrations.AddField(
            model_name='povertyindex',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='povertyindex',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='survey.PovertyIndex'),
        ),
        migrations.AddField(
            model_name='pgpovertyindexshortlistedgrantee',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='pgpovertyindexshortlistedgrantee',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='pgpovertyindexshortlistedgrantee',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='pgpovertyindexshortlistedgrantee',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='survey.PGPovertyIndexShortListedGrantee'),
        ),
        migrations.AddField(
            model_name='pgpovertyindexshortlistedgrantee',
            name='survey_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyResponse'),
        ),
        migrations.AddField(
            model_name='pgpovertyindex',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='pgpovertyindex',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='pgpovertyindex',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='pgpovertyindex',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='survey.PGPovertyIndex'),
        ),
        migrations.AddField(
            model_name='pgpovertyindex',
            name='primary_group_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nuprp_admin.PrimaryGroupMember'),
        ),
        migrations.AddField(
            model_name='pgmpiindicator',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='pgmpiindicator',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='pgmpiindicator',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='pgmpiindicator',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='survey.PGMPIIndicator'),
        ),
        migrations.AddField(
            model_name='pgmpiindicator',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='pgmpiindicator',
            name='primary_group_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nuprp_admin.PrimaryGroupMember'),
        ),
        migrations.AddField(
            model_name='pgmpiindicator',
            name='survey_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyResponse'),
        ),
        migrations.AddField(
            model_name='mpiindicator',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='mpiindicator',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='mpiindicator',
            name='household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nuprp_admin.Household'),
        ),
        migrations.AddField(
            model_name='mpiindicator',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='mpiindicator',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='survey.MPIIndicator'),
        ),
        migrations.AddField(
            model_name='mpiindicator',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='mpiindicator',
            name='survey_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyResponse'),
        ),
        migrations.AddField(
            model_name='answer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='answer',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='answer',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='answer',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='survey.Answer'),
        ),
        migrations.AddField(
            model_name='answer',
            name='next_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='survey.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.Question'),
        ),
    ]
