# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-01-31 10:21
from __future__ import unicode_literals

import blackwidow.core.mixins.modelmixin.active_inactive_model_mixin
import blackwidow.core.mixins.modelmixin.approval_process_restore_model_mixin
import blackwidow.core.mixins.modelmixin.assignment_tracked_model_mixin
import blackwidow.core.mixins.modelmixin.auditable_model_mixin
import blackwidow.core.mixins.modelmixin.child_container_model_mixin
import blackwidow.core.mixins.modelmixin.coded_model_mixin
import blackwidow.core.mixins.modelmixin.convertible_model_mixin
import blackwidow.core.mixins.modelmixin.details_view_model_mixin
import blackwidow.core.mixins.modelmixin.editable_model_mixin
import blackwidow.core.mixins.modelmixin.exportable_model_mixin
import blackwidow.core.mixins.modelmixin.list_view_model_mixin
import blackwidow.core.mixins.modelmixin.mapped_model_mixin
import blackwidow.core.mixins.modelmixin.prefetch_related_model_mixin
import blackwidow.core.mixins.modelmixin.proxy_model_mixin
import blackwidow.core.mixins.modelmixin.restorable_model_mixin
import blackwidow.core.mixins.modelmixin.restricted_model_mixin
import blackwidow.core.mixins.modelmixin.routed_model_mixin
import blackwidow.core.mixins.modelmixin.searchable_model_mixin
import blackwidow.core.mixins.modelmixin.serializable_model_mixin
import blackwidow.core.mixins.modelmixin.step_back_model_mixin
import blackwidow.core.mixins.modelmixin.versioning_model_mixin
import blackwidow.engine.mixins.modelmixin.queryset_cache_mixin
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsync_id', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('date_created', models.BigIntegerField(default=0, editable=False)),
                ('last_updated', models.BigIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('is_locked', models.BooleanField(default=False, editable=False)),
                ('creation_flag', models.CharField(default='Created', max_length=200)),
                ('type', models.CharField(db_index=True, default='', max_length=200)),
                ('code', models.CharField(default='', max_length=200)),
                ('deleted_level', models.SmallIntegerField(default=0)),
                ('is_version', models.BooleanField(default=False, editable=False)),
                ('text', models.CharField(blank=True, max_length=2048)),
                ('text_en', models.CharField(blank=True, max_length=2048, null=True)),
                ('text_bn', models.CharField(blank=True, max_length=2048, null=True)),
                ('order', models.IntegerField(default=0)),
                ('answer_type', models.CharField(blank=True, max_length=64, null=True)),
                ('answer_code', models.CharField(blank=True, max_length=32, null=True)),
            ],
            bases=(blackwidow.core.mixins.modelmixin.list_view_model_mixin.ListViewModelMixin, blackwidow.core.mixins.modelmixin.details_view_model_mixin.DetailsViewModelMixin, blackwidow.core.mixins.modelmixin.serializable_model_mixin.SerializableModelMixin, blackwidow.core.mixins.modelmixin.routed_model_mixin.RoutedModelMixin, blackwidow.core.mixins.modelmixin.auditable_model_mixin.AuditableModelMixin, blackwidow.core.mixins.modelmixin.editable_model_mixin.EditableModelMixin, blackwidow.core.mixins.modelmixin.assignment_tracked_model_mixin.AssignmentTrackedModelMixin, blackwidow.core.mixins.modelmixin.restorable_model_mixin.RestorableModelMixin, blackwidow.core.mixins.modelmixin.proxy_model_mixin.ProxyModelMixin, blackwidow.core.mixins.modelmixin.mapped_model_mixin.MappedModelMixin, blackwidow.core.mixins.modelmixin.coded_model_mixin.CodedModelMixin, blackwidow.core.mixins.modelmixin.child_container_model_mixin.ChildContainerModelMixin, blackwidow.core.mixins.modelmixin.searchable_model_mixin.SearchableModelMixin, blackwidow.core.mixins.modelmixin.restricted_model_mixin.RestrictedModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.MutableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.ApprovableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.RejectableModelMixin, blackwidow.core.mixins.modelmixin.active_inactive_model_mixin.ActiveInactiveModelMixin, blackwidow.core.mixins.modelmixin.step_back_model_mixin.StepBackExecuteModelMixin, blackwidow.core.mixins.modelmixin.approval_process_restore_model_mixin.ApprovalRestoreModelMixin, blackwidow.engine.mixins.modelmixin.queryset_cache_mixin.QuerysetCacheMixin, blackwidow.core.mixins.modelmixin.exportable_model_mixin.ExportableModelMixin, blackwidow.core.mixins.modelmixin.prefetch_related_model_mixin.PrefetchRelatedModelMixin, blackwidow.core.mixins.modelmixin.versioning_model_mixin.VersioningModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DynamicQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsync_id', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('date_created', models.BigIntegerField(default=0, editable=False)),
                ('last_updated', models.BigIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('is_locked', models.BooleanField(default=False, editable=False)),
                ('creation_flag', models.CharField(default='Created', max_length=200)),
                ('type', models.CharField(db_index=True, default='', max_length=200)),
                ('code', models.CharField(default='', max_length=200)),
                ('deleted_level', models.SmallIntegerField(default=0)),
                ('is_version', models.BooleanField(default=False, editable=False)),
                ('text', models.CharField(blank=True, max_length=1024)),
                ('text_en', models.CharField(blank=True, max_length=2048, null=True)),
                ('text_bn', models.CharField(blank=True, max_length=2048, null=True)),
                ('order', models.IntegerField(default=0)),
                ('question_type', models.CharField(blank=True, max_length=64, null=True)),
                ('question_code', models.CharField(blank=True, max_length=32, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('constraint', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('constraint_message', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('default', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('hint', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('dependency_string', models.CharField(blank=True, default='', max_length=2048, null=True)),
                ('count_as_a_parent', models.IntegerField(default=0)),
                ('minimum_image_number', models.IntegerField(default=0)),
                ('repeat_time', models.IntegerField(default=-1)),
                ('assigned_code', models.CharField(blank=True, max_length=63)),
                ('instruction', models.TextField(blank=True)),
                ('translated_instruction', models.TextField(blank=True)),
            ],
            bases=(blackwidow.core.mixins.modelmixin.list_view_model_mixin.ListViewModelMixin, blackwidow.core.mixins.modelmixin.details_view_model_mixin.DetailsViewModelMixin, blackwidow.core.mixins.modelmixin.serializable_model_mixin.SerializableModelMixin, blackwidow.core.mixins.modelmixin.routed_model_mixin.RoutedModelMixin, blackwidow.core.mixins.modelmixin.auditable_model_mixin.AuditableModelMixin, blackwidow.core.mixins.modelmixin.editable_model_mixin.EditableModelMixin, blackwidow.core.mixins.modelmixin.assignment_tracked_model_mixin.AssignmentTrackedModelMixin, blackwidow.core.mixins.modelmixin.restorable_model_mixin.RestorableModelMixin, blackwidow.core.mixins.modelmixin.proxy_model_mixin.ProxyModelMixin, blackwidow.core.mixins.modelmixin.mapped_model_mixin.MappedModelMixin, blackwidow.core.mixins.modelmixin.coded_model_mixin.CodedModelMixin, blackwidow.core.mixins.modelmixin.child_container_model_mixin.ChildContainerModelMixin, blackwidow.core.mixins.modelmixin.searchable_model_mixin.SearchableModelMixin, blackwidow.core.mixins.modelmixin.restricted_model_mixin.RestrictedModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.MutableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.ApprovableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.RejectableModelMixin, blackwidow.core.mixins.modelmixin.active_inactive_model_mixin.ActiveInactiveModelMixin, blackwidow.core.mixins.modelmixin.step_back_model_mixin.StepBackExecuteModelMixin, blackwidow.core.mixins.modelmixin.approval_process_restore_model_mixin.ApprovalRestoreModelMixin, blackwidow.engine.mixins.modelmixin.queryset_cache_mixin.QuerysetCacheMixin, blackwidow.core.mixins.modelmixin.exportable_model_mixin.ExportableModelMixin, blackwidow.core.mixins.modelmixin.prefetch_related_model_mixin.PrefetchRelatedModelMixin, blackwidow.core.mixins.modelmixin.versioning_model_mixin.VersioningModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DynamicQuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsync_id', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('date_created', models.BigIntegerField(default=0, editable=False)),
                ('last_updated', models.BigIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('is_locked', models.BooleanField(default=False, editable=False)),
                ('creation_flag', models.CharField(default='Created', max_length=200)),
                ('type', models.CharField(db_index=True, default='', max_length=200)),
                ('code', models.CharField(default='', max_length=200)),
                ('deleted_level', models.SmallIntegerField(default=0)),
                ('is_version', models.BooleanField(default=False, editable=False)),
                ('question_text', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('answer_text', models.CharField(blank=True, default='', max_length=2048, null=True)),
                ('index', models.IntegerField(default=-1)),
            ],
            bases=(blackwidow.core.mixins.modelmixin.list_view_model_mixin.ListViewModelMixin, blackwidow.core.mixins.modelmixin.details_view_model_mixin.DetailsViewModelMixin, blackwidow.core.mixins.modelmixin.serializable_model_mixin.SerializableModelMixin, blackwidow.core.mixins.modelmixin.routed_model_mixin.RoutedModelMixin, blackwidow.core.mixins.modelmixin.auditable_model_mixin.AuditableModelMixin, blackwidow.core.mixins.modelmixin.editable_model_mixin.EditableModelMixin, blackwidow.core.mixins.modelmixin.assignment_tracked_model_mixin.AssignmentTrackedModelMixin, blackwidow.core.mixins.modelmixin.restorable_model_mixin.RestorableModelMixin, blackwidow.core.mixins.modelmixin.proxy_model_mixin.ProxyModelMixin, blackwidow.core.mixins.modelmixin.mapped_model_mixin.MappedModelMixin, blackwidow.core.mixins.modelmixin.coded_model_mixin.CodedModelMixin, blackwidow.core.mixins.modelmixin.child_container_model_mixin.ChildContainerModelMixin, blackwidow.core.mixins.modelmixin.searchable_model_mixin.SearchableModelMixin, blackwidow.core.mixins.modelmixin.restricted_model_mixin.RestrictedModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.MutableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.ApprovableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.RejectableModelMixin, blackwidow.core.mixins.modelmixin.active_inactive_model_mixin.ActiveInactiveModelMixin, blackwidow.core.mixins.modelmixin.step_back_model_mixin.StepBackExecuteModelMixin, blackwidow.core.mixins.modelmixin.approval_process_restore_model_mixin.ApprovalRestoreModelMixin, blackwidow.engine.mixins.modelmixin.queryset_cache_mixin.QuerysetCacheMixin, blackwidow.core.mixins.modelmixin.exportable_model_mixin.ExportableModelMixin, blackwidow.core.mixins.modelmixin.prefetch_related_model_mixin.PrefetchRelatedModelMixin, blackwidow.core.mixins.modelmixin.versioning_model_mixin.VersioningModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DynamicSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsync_id', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('date_created', models.BigIntegerField(default=0, editable=False)),
                ('last_updated', models.BigIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('is_locked', models.BooleanField(default=False, editable=False)),
                ('creation_flag', models.CharField(default='Created', max_length=200)),
                ('type', models.CharField(db_index=True, default='', max_length=200)),
                ('code', models.CharField(default='', max_length=200)),
                ('deleted_level', models.SmallIntegerField(default=0)),
                ('is_version', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=1024)),
                ('name_en', models.CharField(blank=True, max_length=2048, null=True)),
                ('name_bn', models.CharField(blank=True, max_length=2048, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            bases=(blackwidow.core.mixins.modelmixin.list_view_model_mixin.ListViewModelMixin, blackwidow.core.mixins.modelmixin.details_view_model_mixin.DetailsViewModelMixin, blackwidow.core.mixins.modelmixin.serializable_model_mixin.SerializableModelMixin, blackwidow.core.mixins.modelmixin.routed_model_mixin.RoutedModelMixin, blackwidow.core.mixins.modelmixin.auditable_model_mixin.AuditableModelMixin, blackwidow.core.mixins.modelmixin.editable_model_mixin.EditableModelMixin, blackwidow.core.mixins.modelmixin.assignment_tracked_model_mixin.AssignmentTrackedModelMixin, blackwidow.core.mixins.modelmixin.restorable_model_mixin.RestorableModelMixin, blackwidow.core.mixins.modelmixin.proxy_model_mixin.ProxyModelMixin, blackwidow.core.mixins.modelmixin.mapped_model_mixin.MappedModelMixin, blackwidow.core.mixins.modelmixin.coded_model_mixin.CodedModelMixin, blackwidow.core.mixins.modelmixin.child_container_model_mixin.ChildContainerModelMixin, blackwidow.core.mixins.modelmixin.searchable_model_mixin.SearchableModelMixin, blackwidow.core.mixins.modelmixin.restricted_model_mixin.RestrictedModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.MutableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.ApprovableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.RejectableModelMixin, blackwidow.core.mixins.modelmixin.active_inactive_model_mixin.ActiveInactiveModelMixin, blackwidow.core.mixins.modelmixin.step_back_model_mixin.StepBackExecuteModelMixin, blackwidow.core.mixins.modelmixin.approval_process_restore_model_mixin.ApprovalRestoreModelMixin, blackwidow.engine.mixins.modelmixin.queryset_cache_mixin.QuerysetCacheMixin, blackwidow.core.mixins.modelmixin.exportable_model_mixin.ExportableModelMixin, blackwidow.core.mixins.modelmixin.prefetch_related_model_mixin.PrefetchRelatedModelMixin, blackwidow.core.mixins.modelmixin.versioning_model_mixin.VersioningModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DynamicSectionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsync_id', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('date_created', models.BigIntegerField(default=0, editable=False)),
                ('last_updated', models.BigIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('is_locked', models.BooleanField(default=False, editable=False)),
                ('creation_flag', models.CharField(default='Created', max_length=200)),
                ('type', models.CharField(db_index=True, default='', max_length=200)),
                ('code', models.CharField(default='', max_length=200)),
                ('deleted_level', models.SmallIntegerField(default=0)),
                ('is_version', models.BooleanField(default=False, editable=False)),
            ],
            bases=(blackwidow.core.mixins.modelmixin.list_view_model_mixin.ListViewModelMixin, blackwidow.core.mixins.modelmixin.details_view_model_mixin.DetailsViewModelMixin, blackwidow.core.mixins.modelmixin.serializable_model_mixin.SerializableModelMixin, blackwidow.core.mixins.modelmixin.routed_model_mixin.RoutedModelMixin, blackwidow.core.mixins.modelmixin.auditable_model_mixin.AuditableModelMixin, blackwidow.core.mixins.modelmixin.editable_model_mixin.EditableModelMixin, blackwidow.core.mixins.modelmixin.assignment_tracked_model_mixin.AssignmentTrackedModelMixin, blackwidow.core.mixins.modelmixin.restorable_model_mixin.RestorableModelMixin, blackwidow.core.mixins.modelmixin.proxy_model_mixin.ProxyModelMixin, blackwidow.core.mixins.modelmixin.mapped_model_mixin.MappedModelMixin, blackwidow.core.mixins.modelmixin.coded_model_mixin.CodedModelMixin, blackwidow.core.mixins.modelmixin.child_container_model_mixin.ChildContainerModelMixin, blackwidow.core.mixins.modelmixin.searchable_model_mixin.SearchableModelMixin, blackwidow.core.mixins.modelmixin.restricted_model_mixin.RestrictedModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.MutableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.ApprovableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.RejectableModelMixin, blackwidow.core.mixins.modelmixin.active_inactive_model_mixin.ActiveInactiveModelMixin, blackwidow.core.mixins.modelmixin.step_back_model_mixin.StepBackExecuteModelMixin, blackwidow.core.mixins.modelmixin.approval_process_restore_model_mixin.ApprovalRestoreModelMixin, blackwidow.engine.mixins.modelmixin.queryset_cache_mixin.QuerysetCacheMixin, blackwidow.core.mixins.modelmixin.exportable_model_mixin.ExportableModelMixin, blackwidow.core.mixins.modelmixin.prefetch_related_model_mixin.PrefetchRelatedModelMixin, blackwidow.core.mixins.modelmixin.versioning_model_mixin.VersioningModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DynamicSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsync_id', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('date_created', models.BigIntegerField(default=0, editable=False)),
                ('last_updated', models.BigIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('is_locked', models.BooleanField(default=False, editable=False)),
                ('creation_flag', models.CharField(default='Created', max_length=200)),
                ('type', models.CharField(db_index=True, default='', max_length=200)),
                ('code', models.CharField(default='', max_length=200)),
                ('deleted_level', models.SmallIntegerField(default=0)),
                ('is_version', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('version', models.IntegerField(default=1)),
                ('detail_link', models.CharField(blank=True, default='', max_length=255)),
                ('date_published', models.BigIntegerField(default=0, editable=False)),
                ('latest_flag', models.BooleanField(default=False)),
                ('body', models.TextField()),
                ('description', models.CharField(max_length=255, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('summary', jsonfield.fields.JSONField(default=dict)),
                ('asset_type', models.CharField(max_length=32, null=True)),
                ('kpi_asset_uid', models.CharField(blank=True, default='', max_length=22)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser')),
                ('entity_meta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser')),
                ('master_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='dynamic_survey.DynamicSurvey')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization')),
            ],
            bases=(blackwidow.core.mixins.modelmixin.list_view_model_mixin.ListViewModelMixin, blackwidow.core.mixins.modelmixin.details_view_model_mixin.DetailsViewModelMixin, blackwidow.core.mixins.modelmixin.serializable_model_mixin.SerializableModelMixin, blackwidow.core.mixins.modelmixin.routed_model_mixin.RoutedModelMixin, blackwidow.core.mixins.modelmixin.auditable_model_mixin.AuditableModelMixin, blackwidow.core.mixins.modelmixin.editable_model_mixin.EditableModelMixin, blackwidow.core.mixins.modelmixin.assignment_tracked_model_mixin.AssignmentTrackedModelMixin, blackwidow.core.mixins.modelmixin.restorable_model_mixin.RestorableModelMixin, blackwidow.core.mixins.modelmixin.proxy_model_mixin.ProxyModelMixin, blackwidow.core.mixins.modelmixin.mapped_model_mixin.MappedModelMixin, blackwidow.core.mixins.modelmixin.coded_model_mixin.CodedModelMixin, blackwidow.core.mixins.modelmixin.child_container_model_mixin.ChildContainerModelMixin, blackwidow.core.mixins.modelmixin.searchable_model_mixin.SearchableModelMixin, blackwidow.core.mixins.modelmixin.restricted_model_mixin.RestrictedModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.MutableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.ApprovableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.RejectableModelMixin, blackwidow.core.mixins.modelmixin.active_inactive_model_mixin.ActiveInactiveModelMixin, blackwidow.core.mixins.modelmixin.step_back_model_mixin.StepBackExecuteModelMixin, blackwidow.core.mixins.modelmixin.approval_process_restore_model_mixin.ApprovalRestoreModelMixin, blackwidow.engine.mixins.modelmixin.queryset_cache_mixin.QuerysetCacheMixin, blackwidow.core.mixins.modelmixin.exportable_model_mixin.ExportableModelMixin, blackwidow.core.mixins.modelmixin.prefetch_related_model_mixin.PrefetchRelatedModelMixin, blackwidow.core.mixins.modelmixin.versioning_model_mixin.VersioningModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DynamicSurveyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsync_id', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('date_created', models.BigIntegerField(default=0, editable=False)),
                ('last_updated', models.BigIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('is_locked', models.BooleanField(default=False, editable=False)),
                ('creation_flag', models.CharField(default='Created', max_length=200)),
                ('type', models.CharField(db_index=True, default='', max_length=200)),
                ('code', models.CharField(default='', max_length=200)),
                ('deleted_level', models.SmallIntegerField(default=0)),
                ('is_version', models.BooleanField(default=False, editable=False)),
                ('group_name', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('total_versions', models.IntegerField(default=1)),
                ('publish_flag', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser')),
                ('entity_meta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser')),
                ('master_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='dynamic_survey.DynamicSurveyGroup')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization')),
            ],
            bases=(blackwidow.core.mixins.modelmixin.list_view_model_mixin.ListViewModelMixin, blackwidow.core.mixins.modelmixin.details_view_model_mixin.DetailsViewModelMixin, blackwidow.core.mixins.modelmixin.serializable_model_mixin.SerializableModelMixin, blackwidow.core.mixins.modelmixin.routed_model_mixin.RoutedModelMixin, blackwidow.core.mixins.modelmixin.auditable_model_mixin.AuditableModelMixin, blackwidow.core.mixins.modelmixin.editable_model_mixin.EditableModelMixin, blackwidow.core.mixins.modelmixin.assignment_tracked_model_mixin.AssignmentTrackedModelMixin, blackwidow.core.mixins.modelmixin.restorable_model_mixin.RestorableModelMixin, blackwidow.core.mixins.modelmixin.proxy_model_mixin.ProxyModelMixin, blackwidow.core.mixins.modelmixin.mapped_model_mixin.MappedModelMixin, blackwidow.core.mixins.modelmixin.coded_model_mixin.CodedModelMixin, blackwidow.core.mixins.modelmixin.child_container_model_mixin.ChildContainerModelMixin, blackwidow.core.mixins.modelmixin.searchable_model_mixin.SearchableModelMixin, blackwidow.core.mixins.modelmixin.restricted_model_mixin.RestrictedModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.MutableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.ApprovableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.RejectableModelMixin, blackwidow.core.mixins.modelmixin.active_inactive_model_mixin.ActiveInactiveModelMixin, blackwidow.core.mixins.modelmixin.step_back_model_mixin.StepBackExecuteModelMixin, blackwidow.core.mixins.modelmixin.approval_process_restore_model_mixin.ApprovalRestoreModelMixin, blackwidow.engine.mixins.modelmixin.queryset_cache_mixin.QuerysetCacheMixin, blackwidow.core.mixins.modelmixin.exportable_model_mixin.ExportableModelMixin, blackwidow.core.mixins.modelmixin.prefetch_related_model_mixin.PrefetchRelatedModelMixin, blackwidow.core.mixins.modelmixin.versioning_model_mixin.VersioningModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DynamicSurveyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsync_id', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('date_created', models.BigIntegerField(default=0, editable=False)),
                ('last_updated', models.BigIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('is_locked', models.BooleanField(default=False, editable=False)),
                ('creation_flag', models.CharField(default='Created', max_length=200)),
                ('type', models.CharField(db_index=True, default='', max_length=200)),
                ('code', models.CharField(default='', max_length=200)),
                ('deleted_level', models.SmallIntegerField(default=0)),
                ('is_version', models.BooleanField(default=False, editable=False)),
                ('survey_time', models.BigIntegerField(default=0)),
                ('on_spot_creation_time', models.BigIntegerField(default=0)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ContactAddress')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser')),
                ('entity_meta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Location')),
                ('master_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='dynamic_survey.DynamicSurveyResponse')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization')),
                ('respondent_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Client')),
                ('respondent_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.InfrastructureUnit')),
                ('survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_survey.DynamicSurvey')),
            ],
            bases=(blackwidow.core.mixins.modelmixin.list_view_model_mixin.ListViewModelMixin, blackwidow.core.mixins.modelmixin.details_view_model_mixin.DetailsViewModelMixin, blackwidow.core.mixins.modelmixin.serializable_model_mixin.SerializableModelMixin, blackwidow.core.mixins.modelmixin.routed_model_mixin.RoutedModelMixin, blackwidow.core.mixins.modelmixin.auditable_model_mixin.AuditableModelMixin, blackwidow.core.mixins.modelmixin.editable_model_mixin.EditableModelMixin, blackwidow.core.mixins.modelmixin.assignment_tracked_model_mixin.AssignmentTrackedModelMixin, blackwidow.core.mixins.modelmixin.restorable_model_mixin.RestorableModelMixin, blackwidow.core.mixins.modelmixin.proxy_model_mixin.ProxyModelMixin, blackwidow.core.mixins.modelmixin.mapped_model_mixin.MappedModelMixin, blackwidow.core.mixins.modelmixin.coded_model_mixin.CodedModelMixin, blackwidow.core.mixins.modelmixin.child_container_model_mixin.ChildContainerModelMixin, blackwidow.core.mixins.modelmixin.searchable_model_mixin.SearchableModelMixin, blackwidow.core.mixins.modelmixin.restricted_model_mixin.RestrictedModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.MutableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.ApprovableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.RejectableModelMixin, blackwidow.core.mixins.modelmixin.active_inactive_model_mixin.ActiveInactiveModelMixin, blackwidow.core.mixins.modelmixin.step_back_model_mixin.StepBackExecuteModelMixin, blackwidow.core.mixins.modelmixin.approval_process_restore_model_mixin.ApprovalRestoreModelMixin, blackwidow.engine.mixins.modelmixin.queryset_cache_mixin.QuerysetCacheMixin, blackwidow.core.mixins.modelmixin.exportable_model_mixin.ExportableModelMixin, blackwidow.core.mixins.modelmixin.prefetch_related_model_mixin.PrefetchRelatedModelMixin, blackwidow.core.mixins.modelmixin.versioning_model_mixin.VersioningModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DynamicSurveyResponseGeneratedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsync_id', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('date_created', models.BigIntegerField(default=0, editable=False)),
                ('last_updated', models.BigIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('is_locked', models.BooleanField(default=False, editable=False)),
                ('creation_flag', models.CharField(default='Created', max_length=200)),
                ('type', models.CharField(db_index=True, default='', max_length=200)),
                ('code', models.CharField(default='', max_length=200)),
                ('deleted_level', models.SmallIntegerField(default=0)),
                ('is_version', models.BooleanField(default=False, editable=False)),
                ('month', models.IntegerField(default=1)),
                ('year', models.IntegerField(default=2017)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser')),
                ('entity_meta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta')),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FileObject')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser')),
                ('master_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='dynamic_survey.DynamicSurveyResponseGeneratedFile')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_survey.DynamicSurvey')),
            ],
            bases=(blackwidow.core.mixins.modelmixin.list_view_model_mixin.ListViewModelMixin, blackwidow.core.mixins.modelmixin.details_view_model_mixin.DetailsViewModelMixin, blackwidow.core.mixins.modelmixin.serializable_model_mixin.SerializableModelMixin, blackwidow.core.mixins.modelmixin.routed_model_mixin.RoutedModelMixin, blackwidow.core.mixins.modelmixin.auditable_model_mixin.AuditableModelMixin, blackwidow.core.mixins.modelmixin.editable_model_mixin.EditableModelMixin, blackwidow.core.mixins.modelmixin.assignment_tracked_model_mixin.AssignmentTrackedModelMixin, blackwidow.core.mixins.modelmixin.restorable_model_mixin.RestorableModelMixin, blackwidow.core.mixins.modelmixin.proxy_model_mixin.ProxyModelMixin, blackwidow.core.mixins.modelmixin.mapped_model_mixin.MappedModelMixin, blackwidow.core.mixins.modelmixin.coded_model_mixin.CodedModelMixin, blackwidow.core.mixins.modelmixin.child_container_model_mixin.ChildContainerModelMixin, blackwidow.core.mixins.modelmixin.searchable_model_mixin.SearchableModelMixin, blackwidow.core.mixins.modelmixin.restricted_model_mixin.RestrictedModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.MutableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.ApprovableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.RejectableModelMixin, blackwidow.core.mixins.modelmixin.active_inactive_model_mixin.ActiveInactiveModelMixin, blackwidow.core.mixins.modelmixin.step_back_model_mixin.StepBackExecuteModelMixin, blackwidow.core.mixins.modelmixin.approval_process_restore_model_mixin.ApprovalRestoreModelMixin, blackwidow.engine.mixins.modelmixin.queryset_cache_mixin.QuerysetCacheMixin, blackwidow.core.mixins.modelmixin.exportable_model_mixin.ExportableModelMixin, blackwidow.core.mixins.modelmixin.prefetch_related_model_mixin.PrefetchRelatedModelMixin, blackwidow.core.mixins.modelmixin.versioning_model_mixin.VersioningModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='dynamicsurvey',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_drafts', to='dynamic_survey.DynamicSurveyGroup'),
        ),
    ]
