# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-01-31 10:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dynamic_survey', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0001_initial'),
        ('core', '0002_auto_20220131_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicsurvey',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='dynamicsurvey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dynamicsectionresponse',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='dynamicsectionresponse',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='dynamicsectionresponse',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='dynamicsectionresponse',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='dynamic_survey.DynamicSectionResponse'),
        ),
        migrations.AddField(
            model_name='dynamicsectionresponse',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='dynamicsectionresponse',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_survey.DynamicSection'),
        ),
        migrations.AddField(
            model_name='dynamicsectionresponse',
            name='survey_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_survey.DynamicSurveyResponse'),
        ),
        migrations.AddField(
            model_name='dynamicsection',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='dynamicsection',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='dynamicsection',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='dynamicsection',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='dynamic_survey.DynamicSection'),
        ),
        migrations.AddField(
            model_name='dynamicsection',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='dynamicsection',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic_survey.DynamicSection'),
        ),
        migrations.AddField(
            model_name='dynamicsection',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='dynamic_survey.DynamicSurvey'),
        ),
        migrations.AddField(
            model_name='dynamicquestionresponse',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_survey.DynamicAnswer'),
        ),
        migrations.AddField(
            model_name='dynamicquestionresponse',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='dynamicquestionresponse',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='dynamicquestionresponse',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='dynamicquestionresponse',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='dynamic_survey.DynamicQuestionResponse'),
        ),
        migrations.AddField(
            model_name='dynamicquestionresponse',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='dynamicquestionresponse',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ImageFileObject'),
        ),
        migrations.AddField(
            model_name='dynamicquestionresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_survey.DynamicQuestion'),
        ),
        migrations.AddField(
            model_name='dynamicquestionresponse',
            name='section_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_survey.DynamicSectionResponse'),
        ),
        migrations.AddField(
            model_name='dynamicquestion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='dynamicquestion',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='dynamicquestion',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='dynamicquestion',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='dynamic_survey.DynamicQuestion'),
        ),
        migrations.AddField(
            model_name='dynamicquestion',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='dynamicquestion',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic_survey.DynamicQuestion'),
        ),
        migrations.AddField(
            model_name='dynamicquestion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dynamic_survey.DynamicSection'),
        ),
        migrations.AddField(
            model_name='dynamicanswer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='dynamicanswer',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='dynamicanswer',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='dynamicanswer',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='dynamic_survey.DynamicAnswer'),
        ),
        migrations.AddField(
            model_name='dynamicanswer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='dynamicanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='dynamic_survey.DynamicQuestion'),
        ),
        migrations.CreateModel(
            name='LibraryQuestions',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('dynamic_survey.dynamicsurvey',),
        ),
    ]
