# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-01-31 10:21
from __future__ import unicode_literals

import blackwidow.core.mixins.modelmixin.active_inactive_model_mixin
import blackwidow.core.mixins.modelmixin.approval_process_restore_model_mixin
import blackwidow.core.mixins.modelmixin.assignment_tracked_model_mixin
import blackwidow.core.mixins.modelmixin.auditable_model_mixin
import blackwidow.core.mixins.modelmixin.child_container_model_mixin
import blackwidow.core.mixins.modelmixin.coded_model_mixin
import blackwidow.core.mixins.modelmixin.convertible_model_mixin
import blackwidow.core.mixins.modelmixin.details_view_model_mixin
import blackwidow.core.mixins.modelmixin.editable_model_mixin
import blackwidow.core.mixins.modelmixin.exportable_model_mixin
import blackwidow.core.mixins.modelmixin.list_view_model_mixin
import blackwidow.core.mixins.modelmixin.mapped_model_mixin
import blackwidow.core.mixins.modelmixin.prefetch_related_model_mixin
import blackwidow.core.mixins.modelmixin.proxy_model_mixin
import blackwidow.core.mixins.modelmixin.restorable_model_mixin
import blackwidow.core.mixins.modelmixin.restricted_model_mixin
import blackwidow.core.mixins.modelmixin.routed_model_mixin
import blackwidow.core.mixins.modelmixin.searchable_model_mixin
import blackwidow.core.mixins.modelmixin.serializable_model_mixin
import blackwidow.core.mixins.modelmixin.step_back_model_mixin
import blackwidow.core.mixins.modelmixin.versioning_model_mixin
import blackwidow.engine.mixins.modelmixin.queryset_cache_mixin
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisabledMembersCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsync_id', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('date_created', models.BigIntegerField(default=0, editable=False)),
                ('last_updated', models.BigIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('is_locked', models.BooleanField(default=False, editable=False)),
                ('creation_flag', models.CharField(default='Created', max_length=200)),
                ('type', models.CharField(db_index=True, default='', max_length=200)),
                ('code', models.CharField(default='', max_length=200)),
                ('deleted_level', models.SmallIntegerField(default=0)),
                ('is_version', models.BooleanField(default=False, editable=False)),
                ('disability', models.CharField(blank=True, max_length=255)),
                ('member_count', models.IntegerField(default=0)),
            ],
            bases=(blackwidow.core.mixins.modelmixin.list_view_model_mixin.ListViewModelMixin, blackwidow.core.mixins.modelmixin.details_view_model_mixin.DetailsViewModelMixin, blackwidow.core.mixins.modelmixin.serializable_model_mixin.SerializableModelMixin, blackwidow.core.mixins.modelmixin.routed_model_mixin.RoutedModelMixin, blackwidow.core.mixins.modelmixin.auditable_model_mixin.AuditableModelMixin, blackwidow.core.mixins.modelmixin.editable_model_mixin.EditableModelMixin, blackwidow.core.mixins.modelmixin.assignment_tracked_model_mixin.AssignmentTrackedModelMixin, blackwidow.core.mixins.modelmixin.restorable_model_mixin.RestorableModelMixin, blackwidow.core.mixins.modelmixin.proxy_model_mixin.ProxyModelMixin, blackwidow.core.mixins.modelmixin.mapped_model_mixin.MappedModelMixin, blackwidow.core.mixins.modelmixin.coded_model_mixin.CodedModelMixin, blackwidow.core.mixins.modelmixin.child_container_model_mixin.ChildContainerModelMixin, blackwidow.core.mixins.modelmixin.searchable_model_mixin.SearchableModelMixin, blackwidow.core.mixins.modelmixin.restricted_model_mixin.RestrictedModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.MutableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.ApprovableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.RejectableModelMixin, blackwidow.core.mixins.modelmixin.active_inactive_model_mixin.ActiveInactiveModelMixin, blackwidow.core.mixins.modelmixin.step_back_model_mixin.StepBackExecuteModelMixin, blackwidow.core.mixins.modelmixin.approval_process_restore_model_mixin.ApprovalRestoreModelMixin, blackwidow.engine.mixins.modelmixin.queryset_cache_mixin.QuerysetCacheMixin, blackwidow.core.mixins.modelmixin.exportable_model_mixin.ExportableModelMixin, blackwidow.core.mixins.modelmixin.prefetch_related_model_mixin.PrefetchRelatedModelMixin, blackwidow.core.mixins.modelmixin.versioning_model_mixin.VersioningModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GrantDisbursementCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsync_id', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('date_created', models.BigIntegerField(default=0, editable=False)),
                ('last_updated', models.BigIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('is_locked', models.BooleanField(default=False, editable=False)),
                ('creation_flag', models.CharField(default='Created', max_length=200)),
                ('type', models.CharField(db_index=True, default='', max_length=200)),
                ('code', models.CharField(default='', max_length=200)),
                ('deleted_level', models.SmallIntegerField(default=0)),
                ('is_version', models.BooleanField(default=False, editable=False)),
                ('grant_type', models.CharField(blank=True, max_length=255)),
                ('disbursement_count', models.IntegerField(default=0)),
            ],
            bases=(blackwidow.core.mixins.modelmixin.list_view_model_mixin.ListViewModelMixin, blackwidow.core.mixins.modelmixin.details_view_model_mixin.DetailsViewModelMixin, blackwidow.core.mixins.modelmixin.serializable_model_mixin.SerializableModelMixin, blackwidow.core.mixins.modelmixin.routed_model_mixin.RoutedModelMixin, blackwidow.core.mixins.modelmixin.auditable_model_mixin.AuditableModelMixin, blackwidow.core.mixins.modelmixin.editable_model_mixin.EditableModelMixin, blackwidow.core.mixins.modelmixin.assignment_tracked_model_mixin.AssignmentTrackedModelMixin, blackwidow.core.mixins.modelmixin.restorable_model_mixin.RestorableModelMixin, blackwidow.core.mixins.modelmixin.proxy_model_mixin.ProxyModelMixin, blackwidow.core.mixins.modelmixin.mapped_model_mixin.MappedModelMixin, blackwidow.core.mixins.modelmixin.coded_model_mixin.CodedModelMixin, blackwidow.core.mixins.modelmixin.child_container_model_mixin.ChildContainerModelMixin, blackwidow.core.mixins.modelmixin.searchable_model_mixin.SearchableModelMixin, blackwidow.core.mixins.modelmixin.restricted_model_mixin.RestrictedModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.MutableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.ApprovableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.RejectableModelMixin, blackwidow.core.mixins.modelmixin.active_inactive_model_mixin.ActiveInactiveModelMixin, blackwidow.core.mixins.modelmixin.step_back_model_mixin.StepBackExecuteModelMixin, blackwidow.core.mixins.modelmixin.approval_process_restore_model_mixin.ApprovalRestoreModelMixin, blackwidow.engine.mixins.modelmixin.queryset_cache_mixin.QuerysetCacheMixin, blackwidow.core.mixins.modelmixin.exportable_model_mixin.ExportableModelMixin, blackwidow.core.mixins.modelmixin.prefetch_related_model_mixin.PrefetchRelatedModelMixin, blackwidow.core.mixins.modelmixin.versioning_model_mixin.VersioningModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='KeyValueCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsync_id', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('date_created', models.BigIntegerField(default=0, editable=False)),
                ('last_updated', models.BigIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('is_locked', models.BooleanField(default=False, editable=False)),
                ('creation_flag', models.CharField(default='Created', max_length=200)),
                ('type', models.CharField(db_index=True, default='', max_length=200)),
                ('code', models.CharField(default='', max_length=200)),
                ('deleted_level', models.SmallIntegerField(default=0)),
                ('is_version', models.BooleanField(default=False, editable=False)),
                ('label', models.CharField(blank=True, max_length=512)),
                ('count', models.IntegerField(default=0)),
            ],
            bases=(blackwidow.core.mixins.modelmixin.list_view_model_mixin.ListViewModelMixin, blackwidow.core.mixins.modelmixin.details_view_model_mixin.DetailsViewModelMixin, blackwidow.core.mixins.modelmixin.serializable_model_mixin.SerializableModelMixin, blackwidow.core.mixins.modelmixin.routed_model_mixin.RoutedModelMixin, blackwidow.core.mixins.modelmixin.auditable_model_mixin.AuditableModelMixin, blackwidow.core.mixins.modelmixin.editable_model_mixin.EditableModelMixin, blackwidow.core.mixins.modelmixin.assignment_tracked_model_mixin.AssignmentTrackedModelMixin, blackwidow.core.mixins.modelmixin.restorable_model_mixin.RestorableModelMixin, blackwidow.core.mixins.modelmixin.proxy_model_mixin.ProxyModelMixin, blackwidow.core.mixins.modelmixin.mapped_model_mixin.MappedModelMixin, blackwidow.core.mixins.modelmixin.coded_model_mixin.CodedModelMixin, blackwidow.core.mixins.modelmixin.child_container_model_mixin.ChildContainerModelMixin, blackwidow.core.mixins.modelmixin.searchable_model_mixin.SearchableModelMixin, blackwidow.core.mixins.modelmixin.restricted_model_mixin.RestrictedModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.MutableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.ApprovableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.RejectableModelMixin, blackwidow.core.mixins.modelmixin.active_inactive_model_mixin.ActiveInactiveModelMixin, blackwidow.core.mixins.modelmixin.step_back_model_mixin.StepBackExecuteModelMixin, blackwidow.core.mixins.modelmixin.approval_process_restore_model_mixin.ApprovalRestoreModelMixin, blackwidow.engine.mixins.modelmixin.queryset_cache_mixin.QuerysetCacheMixin, blackwidow.core.mixins.modelmixin.exportable_model_mixin.ExportableModelMixin, blackwidow.core.mixins.modelmixin.prefetch_related_model_mixin.PrefetchRelatedModelMixin, blackwidow.core.mixins.modelmixin.versioning_model_mixin.VersioningModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PGMemberCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsync_id', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('date_created', models.BigIntegerField(default=0, editable=False)),
                ('last_updated', models.BigIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('is_locked', models.BooleanField(default=False, editable=False)),
                ('creation_flag', models.CharField(default='Created', max_length=200)),
                ('type', models.CharField(db_index=True, default='', max_length=200)),
                ('code', models.CharField(default='', max_length=200)),
                ('deleted_level', models.SmallIntegerField(default=0)),
                ('is_version', models.BooleanField(default=False, editable=False)),
                ('pg_member_count', models.IntegerField(default=0)),
            ],
            bases=(blackwidow.core.mixins.modelmixin.list_view_model_mixin.ListViewModelMixin, blackwidow.core.mixins.modelmixin.details_view_model_mixin.DetailsViewModelMixin, blackwidow.core.mixins.modelmixin.serializable_model_mixin.SerializableModelMixin, blackwidow.core.mixins.modelmixin.routed_model_mixin.RoutedModelMixin, blackwidow.core.mixins.modelmixin.auditable_model_mixin.AuditableModelMixin, blackwidow.core.mixins.modelmixin.editable_model_mixin.EditableModelMixin, blackwidow.core.mixins.modelmixin.assignment_tracked_model_mixin.AssignmentTrackedModelMixin, blackwidow.core.mixins.modelmixin.restorable_model_mixin.RestorableModelMixin, blackwidow.core.mixins.modelmixin.proxy_model_mixin.ProxyModelMixin, blackwidow.core.mixins.modelmixin.mapped_model_mixin.MappedModelMixin, blackwidow.core.mixins.modelmixin.coded_model_mixin.CodedModelMixin, blackwidow.core.mixins.modelmixin.child_container_model_mixin.ChildContainerModelMixin, blackwidow.core.mixins.modelmixin.searchable_model_mixin.SearchableModelMixin, blackwidow.core.mixins.modelmixin.restricted_model_mixin.RestrictedModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.MutableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.ApprovableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.RejectableModelMixin, blackwidow.core.mixins.modelmixin.active_inactive_model_mixin.ActiveInactiveModelMixin, blackwidow.core.mixins.modelmixin.step_back_model_mixin.StepBackExecuteModelMixin, blackwidow.core.mixins.modelmixin.approval_process_restore_model_mixin.ApprovalRestoreModelMixin, blackwidow.engine.mixins.modelmixin.queryset_cache_mixin.QuerysetCacheMixin, blackwidow.core.mixins.modelmixin.exportable_model_mixin.ExportableModelMixin, blackwidow.core.mixins.modelmixin.prefetch_related_model_mixin.PrefetchRelatedModelMixin, blackwidow.core.mixins.modelmixin.versioning_model_mixin.VersioningModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PGMemberInfoCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsync_id', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('date_created', models.BigIntegerField(default=0, editable=False)),
                ('last_updated', models.BigIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('is_locked', models.BooleanField(default=False, editable=False)),
                ('creation_flag', models.CharField(default='Created', max_length=200)),
                ('type', models.CharField(db_index=True, default='', max_length=200)),
                ('code', models.CharField(default='', max_length=200)),
                ('deleted_level', models.SmallIntegerField(default=0)),
                ('is_version', models.BooleanField(default=False, editable=False)),
                ('year', models.IntegerField(default=1970)),
                ('month', models.IntegerField(default=1)),
                ('day', models.IntegerField(default=1)),
                ('from_time', models.BigIntegerField(default=0)),
                ('to_time', models.BigIntegerField(default=86400000)),
                ('pg_count', models.IntegerField(default=0)),
                ('household_head_count', models.IntegerField(default=0)),
                ('household_member_count', models.IntegerField(default=0)),
                ('household_male_member_count', models.IntegerField(default=0)),
                ('household_female_member_count', models.IntegerField(default=0)),
                ('household_pregnancy_count', models.IntegerField(default=0)),
                ('household_lactating_mother_count', models.IntegerField(default=0)),
                ('household_with_lactating_mother_count', models.IntegerField(default=0)),
                ('household_without_lactating_mother_count', models.IntegerField(default=0)),
                ('household_children_count', models.IntegerField(default=0)),
                ('household_with_children_count', models.IntegerField(default=0)),
                ('household_without_children_count', models.IntegerField(default=0)),
                ('household_adolescent_girl_count', models.IntegerField(default=0)),
                ('household_with_adolescent_girl_count', models.IntegerField(default=0)),
                ('household_without_adolescent_girl_count', models.IntegerField(default=0)),
                ('household_disability_count', models.IntegerField(default=0)),
                ('household_with_disability_count', models.IntegerField(default=0)),
                ('household_without_disability_count', models.IntegerField(default=0)),
                ('pg_member_difficulty_counts', models.IntegerField(default=0)),
                ('pg_member_no_difficulty_counts', models.IntegerField(default=0)),
            ],
            bases=(blackwidow.core.mixins.modelmixin.list_view_model_mixin.ListViewModelMixin, blackwidow.core.mixins.modelmixin.details_view_model_mixin.DetailsViewModelMixin, blackwidow.core.mixins.modelmixin.serializable_model_mixin.SerializableModelMixin, blackwidow.core.mixins.modelmixin.routed_model_mixin.RoutedModelMixin, blackwidow.core.mixins.modelmixin.auditable_model_mixin.AuditableModelMixin, blackwidow.core.mixins.modelmixin.editable_model_mixin.EditableModelMixin, blackwidow.core.mixins.modelmixin.assignment_tracked_model_mixin.AssignmentTrackedModelMixin, blackwidow.core.mixins.modelmixin.restorable_model_mixin.RestorableModelMixin, blackwidow.core.mixins.modelmixin.proxy_model_mixin.ProxyModelMixin, blackwidow.core.mixins.modelmixin.mapped_model_mixin.MappedModelMixin, blackwidow.core.mixins.modelmixin.coded_model_mixin.CodedModelMixin, blackwidow.core.mixins.modelmixin.child_container_model_mixin.ChildContainerModelMixin, blackwidow.core.mixins.modelmixin.searchable_model_mixin.SearchableModelMixin, blackwidow.core.mixins.modelmixin.restricted_model_mixin.RestrictedModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.MutableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.ApprovableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.RejectableModelMixin, blackwidow.core.mixins.modelmixin.active_inactive_model_mixin.ActiveInactiveModelMixin, blackwidow.core.mixins.modelmixin.step_back_model_mixin.StepBackExecuteModelMixin, blackwidow.core.mixins.modelmixin.approval_process_restore_model_mixin.ApprovalRestoreModelMixin, blackwidow.engine.mixins.modelmixin.queryset_cache_mixin.QuerysetCacheMixin, blackwidow.core.mixins.modelmixin.exportable_model_mixin.ExportableModelMixin, blackwidow.core.mixins.modelmixin.prefetch_related_model_mixin.PrefetchRelatedModelMixin, blackwidow.core.mixins.modelmixin.versioning_model_mixin.VersioningModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='QuestionResponseCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsync_id', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('date_created', models.BigIntegerField(default=0, editable=False)),
                ('last_updated', models.BigIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('is_locked', models.BooleanField(default=False, editable=False)),
                ('creation_flag', models.CharField(default='Created', max_length=200)),
                ('type', models.CharField(db_index=True, default='', max_length=200)),
                ('code', models.CharField(default='', max_length=200)),
                ('deleted_level', models.SmallIntegerField(default=0)),
                ('is_version', models.BooleanField(default=False, editable=False)),
                ('object_id', models.IntegerField(default=0)),
                ('day', models.IntegerField(db_index=True, default=1)),
                ('month', models.IntegerField(db_index=True, default=1)),
                ('year', models.IntegerField(db_index=True, default=2010)),
                ('ref_time', models.BigIntegerField(db_index=True, default=0)),
                ('survey_count', models.IntegerField(default=0)),
                ('city_name', models.CharField(blank=True, db_index=True, max_length=128)),
                ('question_code', models.CharField(db_index=True, default='', max_length=200)),
                ('question_text', models.CharField(blank=True, max_length=1024)),
                ('answer_text', models.CharField(blank=True, db_index=True, max_length=2048)),
            ],
            options={
                'abstract': False,
            },
            bases=(blackwidow.core.mixins.modelmixin.list_view_model_mixin.ListViewModelMixin, blackwidow.core.mixins.modelmixin.details_view_model_mixin.DetailsViewModelMixin, blackwidow.core.mixins.modelmixin.serializable_model_mixin.SerializableModelMixin, blackwidow.core.mixins.modelmixin.routed_model_mixin.RoutedModelMixin, blackwidow.core.mixins.modelmixin.auditable_model_mixin.AuditableModelMixin, blackwidow.core.mixins.modelmixin.editable_model_mixin.EditableModelMixin, blackwidow.core.mixins.modelmixin.assignment_tracked_model_mixin.AssignmentTrackedModelMixin, blackwidow.core.mixins.modelmixin.restorable_model_mixin.RestorableModelMixin, blackwidow.core.mixins.modelmixin.proxy_model_mixin.ProxyModelMixin, blackwidow.core.mixins.modelmixin.mapped_model_mixin.MappedModelMixin, blackwidow.core.mixins.modelmixin.coded_model_mixin.CodedModelMixin, blackwidow.core.mixins.modelmixin.child_container_model_mixin.ChildContainerModelMixin, blackwidow.core.mixins.modelmixin.searchable_model_mixin.SearchableModelMixin, blackwidow.core.mixins.modelmixin.restricted_model_mixin.RestrictedModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.MutableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.ApprovableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.RejectableModelMixin, blackwidow.core.mixins.modelmixin.active_inactive_model_mixin.ActiveInactiveModelMixin, blackwidow.core.mixins.modelmixin.step_back_model_mixin.StepBackExecuteModelMixin, blackwidow.core.mixins.modelmixin.approval_process_restore_model_mixin.ApprovalRestoreModelMixin, blackwidow.engine.mixins.modelmixin.queryset_cache_mixin.QuerysetCacheMixin, blackwidow.core.mixins.modelmixin.exportable_model_mixin.ExportableModelMixin, blackwidow.core.mixins.modelmixin.prefetch_related_model_mixin.PrefetchRelatedModelMixin, blackwidow.core.mixins.modelmixin.versioning_model_mixin.VersioningModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsync_id', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('date_created', models.BigIntegerField(default=0, editable=False)),
                ('last_updated', models.BigIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('is_locked', models.BooleanField(default=False, editable=False)),
                ('creation_flag', models.CharField(default='Created', max_length=200)),
                ('type', models.CharField(db_index=True, default='', max_length=200)),
                ('code', models.CharField(default='', max_length=200)),
                ('deleted_level', models.SmallIntegerField(default=0)),
                ('is_version', models.BooleanField(default=False, editable=False)),
            ],
            bases=(blackwidow.core.mixins.modelmixin.list_view_model_mixin.ListViewModelMixin, blackwidow.core.mixins.modelmixin.details_view_model_mixin.DetailsViewModelMixin, blackwidow.core.mixins.modelmixin.serializable_model_mixin.SerializableModelMixin, blackwidow.core.mixins.modelmixin.routed_model_mixin.RoutedModelMixin, blackwidow.core.mixins.modelmixin.auditable_model_mixin.AuditableModelMixin, blackwidow.core.mixins.modelmixin.editable_model_mixin.EditableModelMixin, blackwidow.core.mixins.modelmixin.assignment_tracked_model_mixin.AssignmentTrackedModelMixin, blackwidow.core.mixins.modelmixin.restorable_model_mixin.RestorableModelMixin, blackwidow.core.mixins.modelmixin.proxy_model_mixin.ProxyModelMixin, blackwidow.core.mixins.modelmixin.mapped_model_mixin.MappedModelMixin, blackwidow.core.mixins.modelmixin.coded_model_mixin.CodedModelMixin, blackwidow.core.mixins.modelmixin.child_container_model_mixin.ChildContainerModelMixin, blackwidow.core.mixins.modelmixin.searchable_model_mixin.SearchableModelMixin, blackwidow.core.mixins.modelmixin.restricted_model_mixin.RestrictedModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.MutableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.ApprovableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.RejectableModelMixin, blackwidow.core.mixins.modelmixin.active_inactive_model_mixin.ActiveInactiveModelMixin, blackwidow.core.mixins.modelmixin.step_back_model_mixin.StepBackExecuteModelMixin, blackwidow.core.mixins.modelmixin.approval_process_restore_model_mixin.ApprovalRestoreModelMixin, blackwidow.engine.mixins.modelmixin.queryset_cache_mixin.QuerysetCacheMixin, blackwidow.core.mixins.modelmixin.exportable_model_mixin.ExportableModelMixin, blackwidow.core.mixins.modelmixin.prefetch_related_model_mixin.PrefetchRelatedModelMixin, blackwidow.core.mixins.modelmixin.versioning_model_mixin.VersioningModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SEFGranteesInfoCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsync_id', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('date_created', models.BigIntegerField(default=0, editable=False)),
                ('last_updated', models.BigIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('is_locked', models.BooleanField(default=False, editable=False)),
                ('creation_flag', models.CharField(default='Created', max_length=200)),
                ('type', models.CharField(db_index=True, default='', max_length=200)),
                ('code', models.CharField(default='', max_length=200)),
                ('deleted_level', models.SmallIntegerField(default=0)),
                ('is_version', models.BooleanField(default=False, editable=False)),
                ('year', models.IntegerField(default=1970)),
                ('month', models.IntegerField(default=1)),
                ('day', models.IntegerField(default=1)),
                ('ward', models.CharField(blank=True, max_length=20, null=True)),
                ('no_of_business_grantee', models.IntegerField(default=0)),
                ('no_of_apprenticeship_grantee', models.IntegerField(default=0)),
                ('no_of_education_dropout_grantee', models.IntegerField(default=0)),
                ('no_education_early_marriage_grantee', models.IntegerField(default=0)),
                ('no_of_nutrition_grantees', models.IntegerField(default=0)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Geography')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser')),
                ('entity_meta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser')),
                ('master_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='reports.SEFGranteesInfoCache')),
            ],
            bases=(blackwidow.core.mixins.modelmixin.list_view_model_mixin.ListViewModelMixin, blackwidow.core.mixins.modelmixin.details_view_model_mixin.DetailsViewModelMixin, blackwidow.core.mixins.modelmixin.serializable_model_mixin.SerializableModelMixin, blackwidow.core.mixins.modelmixin.routed_model_mixin.RoutedModelMixin, blackwidow.core.mixins.modelmixin.auditable_model_mixin.AuditableModelMixin, blackwidow.core.mixins.modelmixin.editable_model_mixin.EditableModelMixin, blackwidow.core.mixins.modelmixin.assignment_tracked_model_mixin.AssignmentTrackedModelMixin, blackwidow.core.mixins.modelmixin.restorable_model_mixin.RestorableModelMixin, blackwidow.core.mixins.modelmixin.proxy_model_mixin.ProxyModelMixin, blackwidow.core.mixins.modelmixin.mapped_model_mixin.MappedModelMixin, blackwidow.core.mixins.modelmixin.coded_model_mixin.CodedModelMixin, blackwidow.core.mixins.modelmixin.child_container_model_mixin.ChildContainerModelMixin, blackwidow.core.mixins.modelmixin.searchable_model_mixin.SearchableModelMixin, blackwidow.core.mixins.modelmixin.restricted_model_mixin.RestrictedModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.MutableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.ApprovableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.RejectableModelMixin, blackwidow.core.mixins.modelmixin.active_inactive_model_mixin.ActiveInactiveModelMixin, blackwidow.core.mixins.modelmixin.step_back_model_mixin.StepBackExecuteModelMixin, blackwidow.core.mixins.modelmixin.approval_process_restore_model_mixin.ApprovalRestoreModelMixin, blackwidow.engine.mixins.modelmixin.queryset_cache_mixin.QuerysetCacheMixin, blackwidow.core.mixins.modelmixin.exportable_model_mixin.ExportableModelMixin, blackwidow.core.mixins.modelmixin.prefetch_related_model_mixin.PrefetchRelatedModelMixin, blackwidow.core.mixins.modelmixin.versioning_model_mixin.VersioningModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SurveyStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsync_id', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('date_created', models.BigIntegerField(default=0, editable=False)),
                ('last_updated', models.BigIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('is_locked', models.BooleanField(default=False, editable=False)),
                ('creation_flag', models.CharField(default='Created', max_length=200)),
                ('type', models.CharField(db_index=True, default='', max_length=200)),
                ('code', models.CharField(default='', max_length=200)),
                ('deleted_level', models.SmallIntegerField(default=0)),
                ('is_version', models.BooleanField(default=False, editable=False)),
                ('survey_name', models.CharField(default='', max_length=255, null=True)),
                ('survey_key', models.CharField(default='', max_length=255, null=True)),
                ('count_response_daily', models.IntegerField(default=0)),
                ('count_response_monthly', models.IntegerField(default=0)),
                ('count_response_all', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser')),
                ('entity_meta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser')),
                ('master_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='reports.SurveyStatistics')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization')),
                ('survey_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ConsoleUser')),
            ],
            bases=(blackwidow.core.mixins.modelmixin.list_view_model_mixin.ListViewModelMixin, blackwidow.core.mixins.modelmixin.details_view_model_mixin.DetailsViewModelMixin, blackwidow.core.mixins.modelmixin.serializable_model_mixin.SerializableModelMixin, blackwidow.core.mixins.modelmixin.routed_model_mixin.RoutedModelMixin, blackwidow.core.mixins.modelmixin.auditable_model_mixin.AuditableModelMixin, blackwidow.core.mixins.modelmixin.editable_model_mixin.EditableModelMixin, blackwidow.core.mixins.modelmixin.assignment_tracked_model_mixin.AssignmentTrackedModelMixin, blackwidow.core.mixins.modelmixin.restorable_model_mixin.RestorableModelMixin, blackwidow.core.mixins.modelmixin.proxy_model_mixin.ProxyModelMixin, blackwidow.core.mixins.modelmixin.mapped_model_mixin.MappedModelMixin, blackwidow.core.mixins.modelmixin.coded_model_mixin.CodedModelMixin, blackwidow.core.mixins.modelmixin.child_container_model_mixin.ChildContainerModelMixin, blackwidow.core.mixins.modelmixin.searchable_model_mixin.SearchableModelMixin, blackwidow.core.mixins.modelmixin.restricted_model_mixin.RestrictedModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.MutableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.ApprovableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.RejectableModelMixin, blackwidow.core.mixins.modelmixin.active_inactive_model_mixin.ActiveInactiveModelMixin, blackwidow.core.mixins.modelmixin.step_back_model_mixin.StepBackExecuteModelMixin, blackwidow.core.mixins.modelmixin.approval_process_restore_model_mixin.ApprovalRestoreModelMixin, blackwidow.engine.mixins.modelmixin.queryset_cache_mixin.QuerysetCacheMixin, blackwidow.core.mixins.modelmixin.exportable_model_mixin.ExportableModelMixin, blackwidow.core.mixins.modelmixin.prefetch_related_model_mixin.PrefetchRelatedModelMixin, blackwidow.core.mixins.modelmixin.versioning_model_mixin.VersioningModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CollapsableReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.Report')),
            ],
            options={
                'abstract': False,
            },
            bases=('reports.report',),
        ),
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='report',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='report',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='report',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='reports.Report'),
        ),
        migrations.AddField(
            model_name='report',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
    ]
