# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-01-31 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('core', '0002_auto_20220131_1021'),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponsecache',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Answer'),
        ),
        migrations.AddField(
            model_name='questionresponsecache',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_city', to='core.Geography'),
        ),
        migrations.AddField(
            model_name='questionresponsecache',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='questionresponsecache',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_division', to='core.Geography'),
        ),
        migrations.AddField(
            model_name='questionresponsecache',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='questionresponsecache',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='questionresponsecache',
            name='mahalla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_mahalla', to='core.Geography'),
        ),
        migrations.AddField(
            model_name='questionresponsecache',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='reports.QuestionResponseCache'),
        ),
        migrations.AddField(
            model_name='questionresponsecache',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='questionresponsecache',
            name='poor_settlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_poor_settlement', to='core.Geography'),
        ),
        migrations.AddField(
            model_name='questionresponsecache',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Question'),
        ),
        migrations.AddField(
            model_name='questionresponsecache',
            name='section_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SectionResponse'),
        ),
        migrations.AddField(
            model_name='questionresponsecache',
            name='survey_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyResponse'),
        ),
        migrations.AddField(
            model_name='questionresponsecache',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_ward', to='core.Geography'),
        ),
        migrations.AddField(
            model_name='pgmemberinfocache',
            name='age_group_counts',
            field=models.ManyToManyField(related_name='_pgmemberinfocache_age_group_counts_+', to='reports.KeyValueCount'),
        ),
        migrations.AddField(
            model_name='pgmemberinfocache',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Geography'),
        ),
        migrations.AddField(
            model_name='pgmemberinfocache',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='pgmemberinfocache',
            name='difficulty_in_communicating_counts',
            field=models.ManyToManyField(related_name='_pgmemberinfocache_difficulty_in_communicating_counts_+', to='reports.KeyValueCount'),
        ),
        migrations.AddField(
            model_name='pgmemberinfocache',
            name='difficulty_in_hearing_counts',
            field=models.ManyToManyField(related_name='_pgmemberinfocache_difficulty_in_hearing_counts_+', to='reports.KeyValueCount'),
        ),
        migrations.AddField(
            model_name='pgmemberinfocache',
            name='difficulty_in_remembering_counts',
            field=models.ManyToManyField(related_name='_pgmemberinfocache_difficulty_in_remembering_counts_+', to='reports.KeyValueCount'),
        ),
        migrations.AddField(
            model_name='pgmemberinfocache',
            name='difficulty_in_seeing_counts',
            field=models.ManyToManyField(related_name='_pgmemberinfocache_difficulty_in_seeing_counts_+', to='reports.KeyValueCount'),
        ),
        migrations.AddField(
            model_name='pgmemberinfocache',
            name='difficulty_in_self_care_counts',
            field=models.ManyToManyField(related_name='_pgmemberinfocache_difficulty_in_self_care_counts_+', to='reports.KeyValueCount'),
        ),
        migrations.AddField(
            model_name='pgmemberinfocache',
            name='difficulty_in_walking_counts',
            field=models.ManyToManyField(related_name='_pgmemberinfocache_difficulty_in_walking_counts_+', to='reports.KeyValueCount'),
        ),
        migrations.AddField(
            model_name='pgmemberinfocache',
            name='disability_counts',
            field=models.ManyToManyField(related_name='_pgmemberinfocache_disability_counts_+', to='reports.KeyValueCount'),
        ),
        migrations.AddField(
            model_name='pgmemberinfocache',
            name='education_counts',
            field=models.ManyToManyField(related_name='_pgmemberinfocache_education_counts_+', to='reports.KeyValueCount'),
        ),
        migrations.AddField(
            model_name='pgmemberinfocache',
            name='employment_counts',
            field=models.ManyToManyField(related_name='_pgmemberinfocache_employment_counts_+', to='reports.KeyValueCount'),
        ),
        migrations.AddField(
            model_name='pgmemberinfocache',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='pgmemberinfocache',
            name='ethnicity_counts',
            field=models.ManyToManyField(related_name='_pgmemberinfocache_ethnicity_counts_+', to='reports.KeyValueCount'),
        ),
        migrations.AddField(
            model_name='pgmemberinfocache',
            name='gender_counts',
            field=models.ManyToManyField(related_name='_pgmemberinfocache_gender_counts_+', to='reports.KeyValueCount'),
        ),
        migrations.AddField(
            model_name='pgmemberinfocache',
            name='hh_difficulty_in_communicating_counts',
            field=models.ManyToManyField(related_name='_pgmemberinfocache_hh_difficulty_in_communicating_counts_+', to='reports.KeyValueCount'),
        ),
        migrations.AddField(
            model_name='pgmemberinfocache',
            name='hh_difficulty_in_hearing_counts',
            field=models.ManyToManyField(related_name='_pgmemberinfocache_hh_difficulty_in_hearing_counts_+', to='reports.KeyValueCount'),
        ),
        migrations.AddField(
            model_name='pgmemberinfocache',
            name='hh_difficulty_in_remembering_counts',
            field=models.ManyToManyField(related_name='_pgmemberinfocache_hh_difficulty_in_remembering_counts_+', to='reports.KeyValueCount'),
        ),
        migrations.AddField(
            model_name='pgmemberinfocache',
            name='hh_difficulty_in_seeing_counts',
            field=models.ManyToManyField(related_name='_pgmemberinfocache_hh_difficulty_in_seeing_counts_+', to='reports.KeyValueCount'),
        ),
        migrations.AddField(
            model_name='pgmemberinfocache',
            name='hh_difficulty_in_self_care_counts',
            field=models.ManyToManyField(related_name='_pgmemberinfocache_hh_difficulty_in_self_care_counts_+', to='reports.KeyValueCount'),
        ),
        migrations.AddField(
            model_name='pgmemberinfocache',
            name='hh_difficulty_in_walking_counts',
            field=models.ManyToManyField(related_name='_pgmemberinfocache_hh_difficulty_in_walking_counts_+', to='reports.KeyValueCount'),
        ),
        migrations.AddField(
            model_name='pgmemberinfocache',
            name='hh_disability_counts',
            field=models.ManyToManyField(related_name='_pgmemberinfocache_hh_disability_counts_+', to='reports.KeyValueCount'),
        ),
        migrations.AddField(
            model_name='pgmemberinfocache',
            name='hh_education_counts',
            field=models.ManyToManyField(related_name='_pgmemberinfocache_hh_education_counts_+', to='reports.KeyValueCount'),
        ),
        migrations.AddField(
            model_name='pgmemberinfocache',
            name='hh_employment_counts',
            field=models.ManyToManyField(related_name='_pgmemberinfocache_hh_employment_counts_+', to='reports.KeyValueCount'),
        ),
        migrations.AddField(
            model_name='pgmemberinfocache',
            name='hh_gender_counts',
            field=models.ManyToManyField(related_name='_pgmemberinfocache_hh_gender_counts_+', to='reports.KeyValueCount'),
        ),
        migrations.AddField(
            model_name='pgmemberinfocache',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='pgmemberinfocache',
            name='marital_status_counts',
            field=models.ManyToManyField(related_name='_pgmemberinfocache_marital_status_counts_+', to='reports.KeyValueCount'),
        ),
        migrations.AddField(
            model_name='pgmemberinfocache',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='reports.PGMemberInfoCache'),
        ),
        migrations.AddField(
            model_name='pgmemberinfocache',
            name='religion_counts',
            field=models.ManyToManyField(related_name='_pgmemberinfocache_religion_counts_+', to='reports.KeyValueCount'),
        ),
        migrations.AddField(
            model_name='pgmemberinfocache',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Geography'),
        ),
        migrations.AddField(
            model_name='pgmembercount',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Geography'),
        ),
        migrations.AddField(
            model_name='pgmembercount',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='pgmembercount',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='pgmembercount',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='pgmembercount',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='reports.PGMemberCount'),
        ),
        migrations.AddField(
            model_name='keyvaluecount',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='keyvaluecount',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='keyvaluecount',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='keyvaluecount',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='reports.KeyValueCount'),
        ),
        migrations.AddField(
            model_name='grantdisbursementcount',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Geography'),
        ),
        migrations.AddField(
            model_name='grantdisbursementcount',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='grantdisbursementcount',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='grantdisbursementcount',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='grantdisbursementcount',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='reports.GrantDisbursementCount'),
        ),
        migrations.AddField(
            model_name='disabledmemberscount',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Geography'),
        ),
        migrations.AddField(
            model_name='disabledmemberscount',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='disabledmemberscount',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='disabledmemberscount',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='disabledmemberscount',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='reports.DisabledMembersCount'),
        ),
        migrations.CreateModel(
            name='CDCPerformanceReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='CHDFLoanMapReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='ClimateHousingDevelopmentFundReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='CommunitiMobilizationReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='CommunityActionPlanMapReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='CRMIFInterventionMapReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='CRMIFReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='EconomicDevelopmentAndLivelihood',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='EnumeratorHouseholdSurveyStats',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='HouseholdLocationReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='HouseholdSurveyIndicatorReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='HouseholdSurveyStats',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='InfrastructureSIFAndCRMIFReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='LowCostHousingUnitMapReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='MobilizedPrimaryGroupMemberMapReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='NutritionGranteesMapReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='NutritionReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='OAndMFundsReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='PGHHHeadInformationReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='PGHHInformationReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='PGMemberInformationReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='PGMemberLocationReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='PovertyConditionMapReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='ProPoorClimateResilientUrbanStrategyMapReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='SavingsAndCreditReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='SEFGranteesMapReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='SIFInterventionMapReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='SIFReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='SocioEconomicFundGrantReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='SurveyLocationReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='TotalSavingMapReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='TrainingAndAwarenessRaisingReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='UrbanGovernanceAndPlanningReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='UserLoginReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='ViolenceAgainstWomanCommitteeMapReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.CreateModel(
            name='WardPrioritizationMapReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('reports.report',),
        ),
        migrations.AlterIndexTogether(
            name='pgmemberinfocache',
            index_together=set([('year', 'month', 'day')]),
        ),
    ]
