from undp_nuprp.nuprp_admin.views.benificieries.grantee_create_view import GranteeCreateView
from undp_nuprp.nuprp_admin.views.developer.api_worker_view import APIWorkerView
from undp_nuprp.nuprp_admin.views.infrastructure_units.primary_group_member_details_view import PrimaryGroupMemberDetailsView
from undp_nuprp.nuprp_admin.views.infrastructure_units.primary_group_member_print_view import PrimaryGroupMemberPrintView
from undp_nuprp.nuprp_admin.views.response.survey_response_details_view import SurveyResponseDetailsView

__author__ = "generated by make_init"

__all__ = ['GranteeCreateView']
__all__ += ['APIWorkerView']
__all__ += ['PrimaryGroupMemberDetailsView']
__all__ += ['PrimaryGroupMemberPrintView']
__all__ += ['SurveyResponseDetailsView']
