from collections import OrderedDict

from django.core.management import BaseCommand

from undp_nuprp.survey.models import Survey, Question, Answer, QuestionResponse

__author__ = 'Ziaul Haque'


class Command(BaseCommand):
    def handle(self, *args, **options):
        survey = Survey.objects.first()
        answer_queryset = Answer.objects.filter(question__section__survey=survey)
        answer_option_dict = OrderedDict()
        question_dict = self.get_question_dict()
        for answer_object in answer_queryset:
            answer_option_dict[answer_object.answer_code] = answer_object

        total_recovered = 0
        for question_code, answer_dict in question_dict.items():
            question = Question.objects.filter(section__survey=survey, question_code=question_code).first()
            print("Recovering survey data for Question Code: %s" % question_code)
            total_recovered_per_question = 0
            if question:
                answer_options = question.answers.all()
                other_option = answer_options.filter(text='Other').first()

                if other_option or question_code == '5.6.1':
                    if question_code == '5.6.1':
                        updatable_question_response_queryset = QuestionResponse.objects.filter(
                            question=question
                        )
                    else:
                        updatable_question_response_queryset = QuestionResponse.objects.filter(
                            question=question, answer=other_option
                        )
                    for wrong_text, answer_tuple in answer_dict.items():
                        answer_code, correct_text = answer_tuple
                        if answer_code in answer_option_dict.keys():
                            answer_object_id = answer_option_dict[answer_code].pk
                            updatable_question_responses = updatable_question_response_queryset.filter(
                                answer_text=wrong_text
                            )
                            _count = updatable_question_responses.count()
                            total_recovered += _count
                            total_recovered_per_question += _count
                            updatable_question_responses.update(answer_text=correct_text, answer_id=answer_object_id)
            print("Total recovered for Question Code: %s is %d" % (question_code, total_recovered_per_question))
        print("Total Recovered %d" % total_recovered)

    @classmethod
    def get_question_dict(cls):
        question_dict = OrderedDict()

        question_dict['5.2'] = OrderedDict()
        question_dict['5.2']['অন্যান্য'] = ('5.2.1', 'Earth/sand')
        question_dict['5.2']['baper bare'] = ('5.2.1', 'Earth/sand')
        question_dict['5.2']['Cement'] = ('5.2.5', 'Cement')
        question_dict['5.2']['Dung'] = ('5.2.2', 'Dung')
        question_dict['5.2']['Earth/sand'] = ('5.2.1', 'Earth/sand')
        question_dict['5.2']['ghor nai'] = ('5.2.1', 'Earth/sand')
        question_dict['5.2']['Iter'] = ('5.2.5', 'Cement')
        question_dict['5.2']['Meyer bari'] = ('5.2.1', 'Earth/sand')
        question_dict['5.2']['mujaek'] = ('5.2.5', 'Cement')
        question_dict['5.2']['Nai'] = ('5.2.1', 'Earth/sand')
        question_dict['5.2']['paka'] = ('5.2.5', 'Cement')
        question_dict['5.2']['paka bari'] = ('5.2.5', 'Cement')
        question_dict['5.2']['Palm/bamboo'] = ('5.2.4', 'Palm/bamboo')
        question_dict['5.2']['tailes'] = ('5.2.5', 'Cement')
        question_dict['5.2']['tiles'] = ('5.2.5', 'Cement')
        question_dict['5.2']['Tiles'] = ('5.2.5', 'Cement')
        question_dict['5.2']['tin'] = ('5.2.1', 'Earth/sand')
        question_dict['5.2']['Tin'] = ('5.2.1', 'Earth/sand')
        question_dict['5.2']['tinset'] = ('5.2.1', 'Earth/sand')
        question_dict['5.2']['Tinset'] = ('5.2.1', 'Earth/sand')
        question_dict['5.2']['tinshed'] = ('5.2.1', 'Earth/sand')
        question_dict['5.2']['Wood Planks'] = ('5.2.3', 'Wood Planks')

        question_dict['5.4'] = OrderedDict()
        question_dict['5.4']['নাই'] = ('5.4.9', 'No facilities or bush or field')
        question_dict['5.4']['অন্যান্য'] = ('5.4.9', 'No facilities or bush or field')
        question_dict['5.4']['Bucket'] = ('5.4.7', 'Bucket')
        question_dict['5.4']['Composting toilet'] = ('5.4.6', 'Composting toilet')
        question_dict['5.4']['drain jukto latren'] = ('5.4.3', 'Pit latrine without slab / open pit')
        question_dict['5.4']['Flush to septic tank or piped sewer system or pit or drainage'] = (
            '5.4.2', 'Flush to septic tank or piped sewer system or pit or drainage')
        question_dict['5.4']['Flush to unknown place/not sure/DK where'] = (
            '5.4.8', 'Flush to unknown place/not sure/DK where')
        question_dict['5.4']['Hanging toilet/hanging latrine'] = ('5.4.5', 'Hanging toilet/hanging latrine')
        question_dict['5.4']['Meyer Barite thake'] = ('5.4.9', 'No facilities or bush or field')
        question_dict['5.4']['nai'] = ('5.4.9', 'No facilities or bush or field')
        question_dict['5.4']['Nai'] = ('5.4.9', 'No facilities or bush or field')
        question_dict['5.4']['Near Family Toylet Use'] = ('5.4.9', 'No facilities or bush or field')
        question_dict['5.4']['NEIGHBOUR TOILATE'] = ('5.4.9', 'No facilities or bush or field')
        question_dict['5.4']['No facilities or bush or field'] = ('5.4.9', 'No facilities or bush or field')
        question_dict['5.4']['None'] = ('5.4.9', 'No facilities or bush or field')
        question_dict['5.4']['onner'] = ('5.4.9', 'No facilities or bush or field')
        question_dict['5.4']['Onner'] = ('5.4.9', 'No facilities or bush or field')
        question_dict['5.4']['onner barthroom'] = ('5.4.9', 'No facilities or bush or field')
        question_dict['5.4']['Onner basai'] = ('5.4.9', 'No facilities or bush or field')
        question_dict['5.4']['Onner ta'] = ('5.4.9', 'No facilities or bush or field')
        question_dict['5.4']['Onner ta use koren'] = ('5.4.9', 'No facilities or bush or field')
        question_dict['5.4']['onno joner'] = ('5.4.9', 'No facilities or bush or field')
        question_dict['5.4']['Others'] = ('5.4.9', 'No facilities or bush or field')
        question_dict['5.4']['Pit latrine with slab'] = ('5.4.1', 'Pit latrine with slab')
        question_dict['5.4']['Pit latrine without slab / open pit'] = (
            '5.4.2', 'Flush to septic tank or piped sewer system or pit or drainage')
        question_dict['5.4']['siment'] = ('5.4.1', 'Pit latrine with slab')
        question_dict['5.4']['tiner'] = ('5.4.1', 'Pit latrine with slab')
        question_dict['5.4']['Tiner Ghera'] = ('5.4.1', 'Pit latrine with slab')
        question_dict['5.4']['Tiner gherowa'] = ('5.4.1', 'Pit latrine with slab')
        question_dict['5.4']['Ventilated Improved Pit latrine (VIP)'] = (
        '5.4.4', 'Ventilated Improved Pit latrine (VIP)')

        question_dict['5.5'] = OrderedDict()
        question_dict['5.5']['অন্যান্য'] = ('5.5.8', 'Wood')
        question_dict['5.5']['Agricultural crop'] = ('5.5.10', 'Agricultural crop')
        question_dict['5.5']['Animal dung'] = ('5.5.11', 'Animal dung')
        question_dict['5.5']['Bara Gass Cula'] = ('5.5.3', 'Natural gas')
        question_dict['5.5']['Biogas'] = ('5.5.4', 'Biogas')
        question_dict['5.5']['Charcoal'] = ('5.5.7', 'Charcoal')
        question_dict['5.5']['Coal / Lignite'] = ('5.5.6', 'Coal / Lignite')
        question_dict['5.5']['Electricity'] = ('5.5.1', 'Electricity')
        question_dict['5.5']['Gass Cula Bara'] = ('5.5.3', 'Natural gas')
        question_dict['5.5']['karchupi'] = ('5.5.1', 'Electricity')
        question_dict['5.5']['Kerosene'] = ('5.5.5', 'Kerosene')
        question_dict['5.5']['lagri'] = ('5.5.8', 'Wood')
        question_dict['5.5']['lagri chola'] = ('5.5.8', 'Wood')
        question_dict['5.5']['lakri'] = ('5.5.8', 'Wood')
        question_dict['5.5']['lakri chola'] = ('5.5.8', 'Wood')
        question_dict['5.5']['lakri chols'] = ('5.5.8', 'Wood')
        question_dict['5.5']['lakri cholw'] = ('5.5.8', 'Wood')
        question_dict['5.5']['lakri cholw'] = ('5.5.8', 'Wood')
        question_dict['5.5']['lakri chula'] = ('5.5.8', 'Wood')
        question_dict['5.5']['lakri cjola'] = ('5.5.8', 'Wood')
        question_dict['5.5']['lakrichola'] = ('5.5.8', 'Wood')
        question_dict['5.5']['Liquid Petroleum Gas (LPG)'] = ('5.5.2', 'Liquid Petroleum Gas (LPG)')
        question_dict['5.5']['lskri chola'] = ('5.5.8', 'Wood')
        question_dict['5.5']['Nai'] = ('5.5.12', 'No Food Cooked in Household')
        question_dict['5.5']['Natural gas'] = ('5.5.3', 'Natural gas')
        question_dict['5.5']['No Food Cooked in Household'] = ('5.5.12', 'No Food Cooked in Household')
        question_dict['5.5']['None'] = ('5.5.12', 'No Food Cooked in Household')
        question_dict['5.5']['onner gas'] = ('5.5.12', 'No Food Cooked in Household')
        question_dict['5.5']['Straw/shrubs/grass'] = ('5.5.9', 'Straw/shrubs/grass')
        question_dict['5.5']['Wood'] = ('5.5.8', 'Wood')

        question_dict['5.6'] = OrderedDict()
        question_dict['5.6']["'3"] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['অন্যর বাসা থেকে আনে'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['অন্যান্য'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['anner bari theke pani ana hoy'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['anner basa theke pani ante hoy'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['Bottled Water'] = ('5.6.13', 'Bottled Water')
        question_dict['5.6']['Cart with small tank/drum'] = ('5.6.11', 'Cart with small tank/drum')
        question_dict['5.6']['motor line'] = ('5.6.1', 'Piped into dwelling')
        question_dict['5.6']['None'] = ('5.6.6', 'Unprotected well')
        question_dict['5.6']['oawsha'] = ('5.6.1', 'Piped into dwelling')
        question_dict['5.6']['onar basa thake ane'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['Oneer Bari theka ane'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['oneer basar theka'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['Oneer basar theka ane'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['onnar'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['onner'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['Onner'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['onner bari theka'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['onner bari theke pani ana hoy'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['Onner basa'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['onner basar theka'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['onner basar theka ane'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['Onner basa theke niye asen'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['onner basar theka'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['Onner basar theka'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['onner basar theka ane'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['Onner basar theka ane'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['Onner Basar theka ane'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['Onner koler theka ane'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['Onner ta use koren'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['Onno Basar theka niya ase'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['Out Of House'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['Out Of House Ariea'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['Out Of My House'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['owasha'] = ('5.6.1', 'Piped into dwelling')
        question_dict['5.6']['Piped into dwelling'] = ('5.6.1', 'Piped into dwelling')
        question_dict['5.6']['Piped into yard or plot'] = ('5.6.2', 'Piped into yard or plot')
        question_dict['5.6']['Protected well'] = ('5.6.5', 'Unprotected well')
        question_dict['5.6']['Public tap/standpipe'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['Rainwater'] = ('5.6.9', 'Rainwater')
        question_dict['5.6']['Rastr theka ane'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['Saplai'] = ('5.6.1', 'Piped into dwelling')
        question_dict['5.6']['Saplai water'] = ('5.6.1', 'Piped into dwelling')
        question_dict['5.6']['Surface water (river, stream, dam, lake, pond, canal, irrigation channel)'] = (
            '5.6.12', 'Surface water (river, stream, dam, lake, pond, canal, irrigation channel)')
        question_dict['5.6']['Tanker-truck'] = ('5.6.10', 'Tanker-truck')
        question_dict['5.6']['Total House Ariea No Water Line'] = ('5.6.3', 'Public tap/standpipe')
        question_dict['5.6']['Tubewell/borehole'] = ('5.6.4', 'Tubewell/borehole')
        question_dict['5.6']['Tubewell/borehole'] = ('5.6.8', 'Unprotected spring')
        question_dict['5.6']['Unprotected well'] = ('5.6.6', 'Unprotected well')

        question_dict['5.6.1'] = OrderedDict()
        question_dict['5.6.1'][''] = ('5.6.1.5', 'More than 30 minutes')
        question_dict['5.6.1']['-10'] = ('5.6.1.2', '5-10 minutes')
        question_dict['5.6.1'][',10'] = ('5.6.1.2', '5-10 minutes')
        question_dict['5.6.1'][',40'] = ('5.6.1.5', 'More than 30 minutes')
        question_dict['5.6.1'][',7'] = ('5.6.1.2', '5-10 minutes')
        question_dict['5.6.1']["0"] = ('5.6.1.1', 'On Premise')
        question_dict['5.6.1']['1'] = ('5.6.1.1', 'On Premise')
        question_dict['5.6.1']["10"] = ('5.6.1.2', '5-10 minutes')
        question_dict['5.6.1']["10 mint"] = ('5.6.1.2', '5-10 minutes')
        question_dict['5.6.1']["10 minute"] = ('5.6.1.2', '5-10 minutes')
        question_dict['5.6.1']["10/ MINITE"] = ('5.6.1.2', '5-10 minutes')
        question_dict['5.6.1']["10minute"] = ('5.6.1.2', '5-10 minutes')
        question_dict['5.6.1']["11"] = ('5.6.1.3', '11-20 minutes')
        question_dict['5.6.1']["11-20 minutes"] = ('5.6.1.3', '11-20 minutes')
        question_dict['5.6.1']["12"] = ('5.6.1.3', '11-20 minutes')
        question_dict['5.6.1']["12 MINITE"] = ('5.6.1.3', '11-20 minutes')
        question_dict['5.6.1']["13"] = ('5.6.1.3', '11-20 minutes')
        question_dict['5.6.1']["13  / MINITE"] = ('5.6.1.3', '11-20 minutes')
        question_dict['5.6.1']["13 MINITE"] = ('5.6.1.3', '11-20 minutes')
        question_dict['5.6.1']["14"] = ('5.6.1.3', '11-20 minutes')
        question_dict['5.6.1']["15"] = ('5.6.1.3', '11-20 minutes')
        question_dict['5.6.1']["15 minute"] = ('5.6.1.3', '11-20 minutes')
        question_dict['5.6.1']["15/  MINITE"] = ('5.6.1.3', '11-20 minutes')
        question_dict['5.6.1']["15/ MINITE"] = ('5.6.1.3', '11-20 minutes')
        question_dict['5.6.1']["16"] = ('5.6.1.3', '11-20 minutes')
        question_dict['5.6.1']["17"] = ('5.6.1.3', '11-20 minutes')
        question_dict['5.6.1']["18"] = ('5.6.1.3', '11-20 minutes')
        question_dict['5.6.1']["18  MINITE"] = ('5.6.1.3', '11-20 minutes')
        question_dict['5.6.1']["19"] = ('5.6.1.3', '11-20 minutes')
        question_dict['5.6.1']["1o"] = ('5.6.1.2', '5-10 minutes')
        question_dict['5.6.1']["2"] = ('5.6.1.1', 'On Premise')
        question_dict['5.6.1']["20"] = ('5.6.1.3', '11-20 minutes')
        question_dict['5.6.1']["20  MINITE"] = ('5.6.1.3', '11-20 minutes')
        question_dict['5.6.1']["20 MINITE"] = ('5.6.1.3', '11-20 minutes')
        question_dict['5.6.1']["20 minute"] = ('5.6.1.3', '11-20 minutes')
        question_dict['5.6.1']["20 minutr"] = ('5.6.1.3', '11-20 minutes')
        question_dict['5.6.1']["20minute"] = ('5.6.1.3', '11-20 minutes')
        question_dict['5.6.1']["20minutr"] = ('5.6.1.3', '11-20 minutes')
        question_dict['5.6.1']["20time"] = ('5.6.1.3', '11-20 minutes')
        question_dict['5.6.1']["21"] = ('5.6.1.4', '21-30 minutes')
        question_dict['5.6.1']["21-30 minutes"] = ('5.6.1.4', '21-30 minutes')
        question_dict['5.6.1']["23"] = ('5.6.1.4', '21-30 minutes')
        question_dict['5.6.1']["24"] = ('5.6.1.4', '21-30 minutes')
        question_dict['5.6.1']["24/ MINITE"] = ('5.6.1.4', '21-30 minutes')
        question_dict['5.6.1']["25"] = ('5.6.1.4', '21-30 minutes')
        question_dict['5.6.1']["25 minute"] = ('5.6.1.4', '21-30 minutes')
        question_dict['5.6.1']["25/ MINITE"] = ('5.6.1.4', '21-30 minutes')
        question_dict['5.6.1']["25minutr"] = ('5.6.1.4', '21-30 minutes')
        question_dict['5.6.1']["26"] = ('5.6.1.4', '21-30 minutes')
        question_dict['5.6.1']["29"] = ('5.6.1.4', '21-30 minutes')
        question_dict['5.6.1']["2min"] = ('5.6.1.1', 'On Premise')
        question_dict['5.6.1']["2minit"] = ('5.6.1.1', 'On Premise')
        question_dict['5.6.1']["2o"] = ('5.6.1.3', '11-20 minutes')
        question_dict['5.6.1']["3"] = ('5.6.1.1', 'On Premise')
        question_dict['5.6.1']["3 mint"] = ('5.6.1.1', 'On Premise')
        question_dict['5.6.1']["30"] = ('5.6.1.5', 'More than 30 minutes')
        question_dict['5.6.1']["30 minute"] = ('5.6.1.5', 'More than 30 minutes')
        question_dict['5.6.1']["30min"] = ('5.6.1.5', 'More than 30 minutes')
        question_dict['5.6.1']["35"] = ('5.6.1.5', 'More than 30 minutes')
        question_dict['5.6.1']["3min"] = ('5.6.1.1', 'On Premise')
        question_dict['5.6.1']["3o"] = ('5.6.1.5', 'More than 30 minutes')
        question_dict['5.6.1']["4"] = ('5.6.1.1', 'On Premise')
        question_dict['5.6.1']["4/ MINITE"] = ('5.6.1.1', 'On Premise')
        question_dict['5.6.1']["40"] = ('5.6.1.5', 'More than 30 minutes')
        question_dict['5.6.1']["4min"] = ('5.6.1.1', 'On Premise')
        question_dict['5.6.1']["4o"] = ('5.6.1.5', 'More than 30 minutes')
        question_dict['5.6.1']["5"] = ('5.6.1.2', '5-10 minutes')
        question_dict['5.6.1']["5 min"] = ('5.6.1.2', '5-10 minutes')
        question_dict['5.6.1']["5 mint"] = ('5.6.1.2', '5-10 minutes')
        question_dict['5.6.1']["5-10 minutes"] = ('5.6.1.2', '5-10 minutes')
        question_dict['5.6.1']["5/ MINITE"] = ('5.6.1.2', '5-10 minutes')
        question_dict['5.6.1']["50"] = ('5.6.1.5', 'More than 30 minutes')
        question_dict['5.6.1']["5min"] = ('5.6.1.2', '5-10 minutes')
        question_dict['5.6.1']["5mint"] = ('5.6.1.2', '5-10 minutes')
        question_dict['5.6.1']["6"] = ('5.6.1.2', '5-10 minutes')
        question_dict['5.6.1']["6/ MINITE"] = ('5.6.1.2', '5-10 minutes')
        question_dict['5.6.1']["60"] = ('5.6.1.5', 'More than 30 minutes')
        question_dict['5.6.1']["6min"] = ('5.6.1.2', '5-10 minutes')
        question_dict['5.6.1']["7"] = ('5.6.1.2', '5-10 minutes')
        question_dict['5.6.1']["7/ MINITE"] = ('5.6.1.2', '5-10 minutes')
        question_dict['5.6.1']["8"] = ('5.6.1.2', '5-10 minutes')
        question_dict['5.6.1']["9"] = ('5.6.1.2', '5-10 minutes')
        question_dict['5.6.1']["9/ MINITE"] = ('5.6.1.2', '5-10 minutes')
        question_dict['5.6.1']["0"] = ('5.6.1.1', 'On Premise')
        question_dict['5.6.1']["5"] = ('5.6.1.2', '5-10 minutes')
        question_dict['5.6.1']["আসতে যেতে মিনিটে"] = ('5.6.1.1', 'On Premise')
        question_dict['5.6.1']["More than 30 minutes"] = ('5.6.1.5', 'More than 30 minutes')
        question_dict['5.6.1']["On Premise"] = ('5.6.1.1', 'On Premise')

        return question_dict
