"""
Created by tareq on 10/17/17
"""

__author__ = 'Tareq'

SITE_NAME_AS_KEY = 'nuprp'

ONE_HOUR_TIMEOUT = 60 * 60
ONE_DAY_TIMEOUT = 24 * 60 * 60
ONE_WEEK_TIMEOUT = 7 * 24 * 60 * 60
ONE_MONTH_TIMEOUT = 30 * 24 * 60 * 60

CONSOLE_USER_CACHE = SITE_NAME_AS_KEY + '_c_user_'
ORGANIZATION_CACHE = SITE_NAME_AS_KEY + '_c_org_'
USER_TIMEZONE_CACHE = SITE_NAME_AS_KEY + '_tzone_'
ALL_MODULE = SITE_NAME_AS_KEY + '_all_modules_'

MODULE_PERMISSION_TIME_CACHE = SITE_NAME_AS_KEY + '_module_perm_ts_'
ROLE_PERMISSION_TIME_CACHE = SITE_NAME_AS_KEY + '_role_perm_ts_'

GEOGRAPHY_HIERARCHY_CACHE_PREFIX = SITE_NAME_AS_KEY + '_geo_hierarchy_'
GEOGRAPHY_LEVEL_CACHE_PREFIX = SITE_NAME_AS_KEY + '_geo_level_'

PERMISSION_CREATE = SITE_NAME_AS_KEY + '_perm_create_'
PERMISSION_EDIT = SITE_NAME_AS_KEY + '_perm_edit_'
PERMISSION_DELETE = SITE_NAME_AS_KEY + '_perm_delete_'
PERMISSION_VIEW = SITE_NAME_AS_KEY + '_perm_view_'
PERMISSION_NO_ACCESS = SITE_NAME_AS_KEY + '_perm_no_access_'

MODULE_PERMISSION_BY_ROLE = SITE_NAME_AS_KEY + '_module_perm_'
ACCESS_PERMISSION_BY_ROLE = SITE_NAME_AS_KEY + '_access_perm_'

STATUS_API_PREFIX = SITE_NAME_AS_KEY + '_status_'
MODEL_CACHE_PREFIX = SITE_NAME_AS_KEY + '_model_'
LOG_CACHE_PREFIX = SITE_NAME_AS_KEY + '_log_'
DELETED_LIST_PREFIX = SITE_NAME_AS_KEY + '_deleted_'
USER_LOGIN_INFO_PREFIX = SITE_NAME_AS_KEY + '_user_info_'
HELP_INFO_PREFIX = SITE_NAME_AS_KEY + '_help_info_'

DEVICE_STATUS_PREFIX = SITE_NAME_AS_KEY + '_device_'
DEVICE_INITIAL_PREFIX = SITE_NAME_AS_KEY + '_device_initial_'
DEVICE_LOCK_PREFIX = SITE_NAME_AS_KEY + '_device_lock_'
ALLOWED_APPS_PREFIX = SITE_NAME_AS_KEY + '_allowed_apps_'
DEVICE_SETTINGS_PREFIX = SITE_NAME_AS_KEY + '_device_settings_'
FB_APP_PREFIX = SITE_NAME_AS_KEY + '_fb_app_'

SCHEDULER_TASK_QUEUE_CACHE_KEY = SITE_NAME_AS_KEY + '_scheduler_task_queue_'
