# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-01-31 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey', '0002_auto_20220131_1021'),
        ('core', '0002_auto_20220131_1021'),
        ('approvals', '0002_auto_20220131_1021'),
        ('nuprp_admin', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sifandcrmifintervention',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ImageFileObject'),
        ),
        migrations.AddField(
            model_name='sifandcrmifintervention',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='sifandcrmifintervention',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Location'),
        ),
        migrations.AddField(
            model_name='sifandcrmifintervention',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.SIFAndCRMIFIntervention'),
        ),
        migrations.AddField(
            model_name='sifandcrmifintervention',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='sif',
            name='assigned_cdc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nuprp_admin.CDC'),
        ),
        migrations.AddField(
            model_name='sif',
            name='assigned_cdc_cluster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nuprp_admin.CDCCluster'),
        ),
        migrations.AddField(
            model_name='sif',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='sif',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='sif',
            name='installments',
            field=models.ManyToManyField(to='approvals.SIFInstallment'),
        ),
        migrations.AddField(
            model_name='sif',
            name='interventions',
            field=models.ManyToManyField(to='approvals.Intervention'),
        ),
        migrations.AddField(
            model_name='sif',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='sif',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.SIF'),
        ),
        migrations.AddField(
            model_name='sif',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='shortlistedeligiblegrantee',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ContactAddress'),
        ),
        migrations.AddField(
            model_name='shortlistedeligiblegrantee',
            name='cdc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nuprp_admin.CDC'),
        ),
        migrations.AddField(
            model_name='shortlistedeligiblegrantee',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='shortlistedeligiblegrantee',
            name='eligible_grantee_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='shortlistedeligiblegrantee',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='shortlistedeligiblegrantee',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='shortlistedeligiblegrantee',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.ShortListedEligibleGrantee'),
        ),
        migrations.AddField(
            model_name='shortlistedeligiblegrantee',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='shortlistedeligiblegrantee',
            name='pg_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nuprp_admin.PrimaryGroupMember'),
        ),
        migrations.AddField(
            model_name='shortlistedeligiblegrantee',
            name='survey_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.SurveyResponse'),
        ),
        migrations.AddField(
            model_name='seftracker',
            name='cdc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nuprp_admin.CDC'),
        ),
        migrations.AddField(
            model_name='seftracker',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Geography'),
        ),
        migrations.AddField(
            model_name='seftracker',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sef_trackers', to='nuprp_admin.CDCCluster'),
        ),
        migrations.AddField(
            model_name='seftracker',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='seftracker',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='seftracker',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='seftracker',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.SEFTracker'),
        ),
        migrations.AddField(
            model_name='seftracker',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='sefnutritiongrantee',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ContactAddress'),
        ),
        migrations.AddField(
            model_name='sefnutritiongrantee',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='sefnutritiongrantee',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='sefnutritiongrantee',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='sefnutritiongrantee',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.SEFNutritionGrantee'),
        ),
        migrations.AddField(
            model_name='sefnutritiongrantee',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='sefnutritiongrantee',
            name='pg_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nuprp_admin.PrimaryGroupMember'),
        ),
        migrations.AddField(
            model_name='sefnutritiongrantee',
            name='sef_grant_disbursement',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='approvals.SEFGrantDisbursement'),
        ),
        migrations.AddField(
            model_name='sefinstallment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='sefinstallment',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='sefinstallment',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='sefinstallment',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.SEFInstallment'),
        ),
        migrations.AddField(
            model_name='sefinstallment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='sefgrantinstalment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='sefgrantinstalment',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='sefgrantinstalment',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='sefgrantinstalment',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.SEFGrantInstalment'),
        ),
        migrations.AddField(
            model_name='sefgrantinstalment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='sefgrantdisbursement',
            name='cdc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nuprp_admin.CDC'),
        ),
        migrations.AddField(
            model_name='sefgrantdisbursement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='sefgrantdisbursement',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='sefgrantdisbursement',
            name='instalments',
            field=models.ManyToManyField(to='approvals.SEFGrantInstalment'),
        ),
        migrations.AddField(
            model_name='sefgrantdisbursement',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='sefgrantdisbursement',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.SEFGrantDisbursement'),
        ),
        migrations.AddField(
            model_name='sefgrantdisbursement',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='sefgrantdisbursement',
            name='pg_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nuprp_admin.PrimaryGroupMember'),
        ),
        migrations.AddField(
            model_name='sefeducationdropoutgrantee',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ContactAddress'),
        ),
        migrations.AddField(
            model_name='sefeducationdropoutgrantee',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='sefeducationdropoutgrantee',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='sefeducationdropoutgrantee',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='sefeducationdropoutgrantee',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.SEFEducationDropoutGrantee'),
        ),
        migrations.AddField(
            model_name='sefeducationdropoutgrantee',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='sefeducationdropoutgrantee',
            name='pg_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nuprp_admin.PrimaryGroupMember'),
        ),
        migrations.AddField(
            model_name='sefeducationdropoutgrantee',
            name='sef_grant_disbursement',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='approvals.SEFGrantDisbursement'),
        ),
        migrations.AddField(
            model_name='sefeducationchildmarriagegrantee',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ContactAddress'),
        ),
        migrations.AddField(
            model_name='sefeducationchildmarriagegrantee',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='sefeducationchildmarriagegrantee',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='sefeducationchildmarriagegrantee',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='sefeducationchildmarriagegrantee',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.SEFEducationChildMarriageGrantee'),
        ),
        migrations.AddField(
            model_name='sefeducationchildmarriagegrantee',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='sefeducationchildmarriagegrantee',
            name='pg_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nuprp_admin.PrimaryGroupMember'),
        ),
        migrations.AddField(
            model_name='sefeducationchildmarriagegrantee',
            name='sef_grant_disbursement',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='approvals.SEFGrantDisbursement'),
        ),
        migrations.AddField(
            model_name='sefbusinessgrantee',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ContactAddress'),
        ),
        migrations.AddField(
            model_name='sefbusinessgrantee',
            name='business_sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nuprp_admin.BusinessSector'),
        ),
        migrations.AddField(
            model_name='sefbusinessgrantee',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='sefbusinessgrantee',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='sefbusinessgrantee',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='sefbusinessgrantee',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.SEFBusinessGrantee'),
        ),
        migrations.AddField(
            model_name='sefbusinessgrantee',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='sefbusinessgrantee',
            name='pg_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nuprp_admin.PrimaryGroupMember'),
        ),
        migrations.AddField(
            model_name='sefbusinessgrantee',
            name='sef_grant_disbursement',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='approvals.SEFGrantDisbursement'),
        ),
        migrations.AddField(
            model_name='sefbusinessgrantee',
            name='type_of_business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='nuprp_admin.BusinessType'),
        ),
        migrations.AddField(
            model_name='sefapprenticeshipgrantee',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ContactAddress'),
        ),
        migrations.AddField(
            model_name='sefapprenticeshipgrantee',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='sefapprenticeshipgrantee',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='sefapprenticeshipgrantee',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='sefapprenticeshipgrantee',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.SEFApprenticeshipGrantee'),
        ),
        migrations.AddField(
            model_name='sefapprenticeshipgrantee',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='sefapprenticeshipgrantee',
            name='pg_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nuprp_admin.PrimaryGroupMember'),
        ),
        migrations.AddField(
            model_name='sefapprenticeshipgrantee',
            name='sef_grant_disbursement',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='approvals.SEFGrantDisbursement'),
        ),
        migrations.AddField(
            model_name='sefapprenticeshipgrantee',
            name='trade_sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nuprp_admin.TradeSector'),
        ),
        migrations.AddField(
            model_name='sefapprenticeshipgrantee',
            name='trade_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='nuprp_admin.TradeType'),
        ),
        migrations.AddField(
            model_name='scgmonthlyreport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='scgmonthlyreport',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='scgmonthlyreport',
            name='field_values',
            field=models.ManyToManyField(to='core.CustomFieldValue'),
        ),
        migrations.AddField(
            model_name='scgmonthlyreport',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='scgmonthlyreport',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Location'),
        ),
        migrations.AddField(
            model_name='scgmonthlyreport',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.SCGMonthlyReport'),
        ),
        migrations.AddField(
            model_name='scgmonthlyreport',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='scgmonthlyreport',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='approvals.SCGMonthlyReport'),
        ),
        migrations.AddField(
            model_name='scgmonthlyreport',
            name='scg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nuprp_admin.SavingsAndCreditGroup'),
        ),
        migrations.AddField(
            model_name='savingsandcreditreportlog',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='savingsandcreditreportlog',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='savingsandcreditreportlog',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='savingsandcreditreportlog',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.SavingsAndCreditReportlog'),
        ),
        migrations.AddField(
            model_name='savingsandcreditreportlog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='savingsandcreditreportlog',
            name='scg_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='approvals.SCGMonthlyReport'),
        ),
        migrations.AddField(
            model_name='sanitaryintervention',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='sanitaryintervention',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='sanitaryintervention',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='sanitaryintervention',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.SanitaryIntervention'),
        ),
        migrations.AddField(
            model_name='sanitaryintervention',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='safetysecurityinitiative',
            name='attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FileObject'),
        ),
        migrations.AddField(
            model_name='safetysecurityinitiative',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='safetysecurityinitiative',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='safetysecurityinitiative',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='safetysecurityinitiative',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.SafetySecurityInitiative'),
        ),
        migrations.AddField(
            model_name='safetysecurityinitiative',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='quantitativereport',
            name='attached_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FileObject'),
        ),
        migrations.AddField(
            model_name='quantitativereport',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Geography'),
        ),
        migrations.AddField(
            model_name='quantitativereport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='quantitativereport',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='quantitativereport',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='quantitativereport',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.QuantitativeReport'),
        ),
        migrations.AddField(
            model_name='quantitativereport',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='pmfuploadedfilequeue',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='pmfuploadedfilequeue',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='pmfuploadedfilequeue',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FileObject'),
        ),
        migrations.AddField(
            model_name='pmfuploadedfilequeue',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='pmfuploadedfilequeue',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.PMFUploadedFileQueue'),
        ),
        migrations.AddField(
            model_name='pmfuploadedfilequeue',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='pmfuploadedfilequeue',
            name='pmf_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approvals.PMFReport'),
        ),
        migrations.AddField(
            model_name='pmfreport',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Geography'),
        ),
        migrations.AddField(
            model_name='pmfreport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='pmfreport',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='pmfreport',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='pmfreport',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.PMFReport'),
        ),
        migrations.AddField(
            model_name='pmfreport',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='mobilizedprimarygroupmember',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_city', to='core.Geography'),
        ),
        migrations.AddField(
            model_name='mobilizedprimarygroupmember',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='mobilizedprimarygroupmember',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='mobilizedprimarygroupmember',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='mobilizedprimarygroupmember',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.MobilizedPrimaryGroupMember'),
        ),
        migrations.AddField(
            model_name='mobilizedprimarygroupmember',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='mobilizedprimarygroupmember',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_ward', to='core.Geography'),
        ),
        migrations.AddField(
            model_name='lowcosthousingunit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='lowcosthousingunit',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='lowcosthousingunit',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='lowcosthousingunit',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.LowCostHousingUnit'),
        ),
        migrations.AddField(
            model_name='lowcosthousingunit',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='lowcosthousingunit',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Geography'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='completed_contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='approvals.CompletedContract'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.Intervention'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='sanitary_interventions',
            field=models.ManyToManyField(to='approvals.SanitaryIntervention'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='water_interventions',
            field=models.ManyToManyField(to='approvals.WaterIntervention'),
        ),
        migrations.AddField(
            model_name='granteegeneratedfile',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Geography'),
        ),
        migrations.AddField(
            model_name='granteegeneratedfile',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='granteegeneratedfile',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='granteegeneratedfile',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FileObject'),
        ),
        migrations.AddField(
            model_name='granteegeneratedfile',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='granteegeneratedfile',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.GranteeGeneratedFile'),
        ),
        migrations.AddField(
            model_name='functionofscc',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='functionofscc',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='functionofscc',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='functionofscc',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.FunctionOfSCC'),
        ),
        migrations.AddField(
            model_name='functionofscc',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='fieldmonitoringreport',
            name='attachment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FileObject'),
        ),
        migrations.AddField(
            model_name='fieldmonitoringreport',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Geography'),
        ),
        migrations.AddField(
            model_name='fieldmonitoringreport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='fieldmonitoringreport',
            name='email_recipients',
            field=models.ManyToManyField(to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='fieldmonitoringreport',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='fieldmonitoringreport',
            name='key_observations',
            field=models.ManyToManyField(to='approvals.FieldMonitoringFollowup'),
        ),
        migrations.AddField(
            model_name='fieldmonitoringreport',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='fieldmonitoringreport',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.FieldMonitoringReport'),
        ),
        migrations.AddField(
            model_name='fieldmonitoringreport',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='fieldmonitoringreport',
            name='output',
            field=models.ManyToManyField(to='approvals.FieldMonitoringOutput'),
        ),
        migrations.AddField(
            model_name='fieldmonitoringreport',
            name='report_pictures',
            field=models.ManyToManyField(related_name='monitoring_reports', to='core.ImageFileObject'),
        ),
        migrations.AddField(
            model_name='fieldmonitoringoutput',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='fieldmonitoringoutput',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='fieldmonitoringoutput',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='fieldmonitoringoutput',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.FieldMonitoringOutput'),
        ),
        migrations.AddField(
            model_name='fieldmonitoringoutput',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='fieldmonitoringfollowup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='fieldmonitoringfollowup',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='fieldmonitoringfollowup',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='fieldmonitoringfollowup',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.FieldMonitoringFollowup'),
        ),
        migrations.AddField(
            model_name='fieldmonitoringfollowup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='exploredpartnership',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='exploredpartnership',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='exploredpartnership',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='exploredpartnership',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.ExploredPartnership'),
        ),
        migrations.AddField(
            model_name='exploredpartnership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='eligibleeducationgrantee',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ContactAddress'),
        ),
        migrations.AddField(
            model_name='eligibleeducationgrantee',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='eligibleeducationgrantee',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='eligibleeducationgrantee',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='eligibleeducationgrantee',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.EligibleEducationGrantee'),
        ),
        migrations.AddField(
            model_name='eligibleeducationgrantee',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='eligibleeducationgrantee',
            name='pg_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nuprp_admin.PrimaryGroupMember'),
        ),
        migrations.AddField(
            model_name='eligibleeducationgrantee',
            name='survey_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.SurveyResponse'),
        ),
        migrations.AddField(
            model_name='eligiblebusinessgrantee',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ContactAddress'),
        ),
        migrations.AddField(
            model_name='eligiblebusinessgrantee',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='eligiblebusinessgrantee',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='eligiblebusinessgrantee',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='eligiblebusinessgrantee',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.EligibleBusinessGrantee'),
        ),
        migrations.AddField(
            model_name='eligiblebusinessgrantee',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='eligiblebusinessgrantee',
            name='pg_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nuprp_admin.PrimaryGroupMember'),
        ),
        migrations.AddField(
            model_name='eligiblebusinessgrantee',
            name='survey_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.SurveyResponse'),
        ),
        migrations.AddField(
            model_name='eligibleapprenticeshipgrantee',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ContactAddress'),
        ),
        migrations.AddField(
            model_name='eligibleapprenticeshipgrantee',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='eligibleapprenticeshipgrantee',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='eligibleapprenticeshipgrantee',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='eligibleapprenticeshipgrantee',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.EligibleApprenticeshipGrantee'),
        ),
        migrations.AddField(
            model_name='eligibleapprenticeshipgrantee',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='eligibleapprenticeshipgrantee',
            name='pg_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nuprp_admin.PrimaryGroupMember'),
        ),
        migrations.AddField(
            model_name='eligibleapprenticeshipgrantee',
            name='survey_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.SurveyResponse'),
        ),
        migrations.AddField(
            model_name='cumulativereport',
            name='cdc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nuprp_admin.CDC'),
        ),
        migrations.AddField(
            model_name='cumulativereport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='cumulativereport',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='cumulativereport',
            name='field_values',
            field=models.ManyToManyField(to='core.CustomFieldValue'),
        ),
        migrations.AddField(
            model_name='cumulativereport',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='cumulativereport',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Location'),
        ),
        migrations.AddField(
            model_name='cumulativereport',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.CumulativeReport'),
        ),
        migrations.AddField(
            model_name='cumulativereport',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='cumulativereport',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='approvals.CumulativeReport'),
        ),
        migrations.AddField(
            model_name='crmif',
            name='assigned_cdc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nuprp_admin.CDC'),
        ),
        migrations.AddField(
            model_name='crmif',
            name='assigned_cdc_cluster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nuprp_admin.CDCCluster'),
        ),
        migrations.AddField(
            model_name='crmif',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='crmif',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='crmif',
            name='installments',
            field=models.ManyToManyField(to='approvals.SIFInstallment'),
        ),
        migrations.AddField(
            model_name='crmif',
            name='interventions',
            field=models.ManyToManyField(to='approvals.Intervention'),
        ),
        migrations.AddField(
            model_name='crmif',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='crmif',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.CRMIF'),
        ),
        migrations.AddField(
            model_name='crmif',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='completedcontract',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='completedcontract',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='completedcontract',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='completedcontract',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.CompletedContract'),
        ),
        migrations.AddField(
            model_name='completedcontract',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='citywisepmfreportachievement',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Geography'),
        ),
        migrations.AddField(
            model_name='citywisepmfreportachievement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='citywisepmfreportachievement',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='citywisepmfreportachievement',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='citywisepmfreportachievement',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.CityWisePMFReportAchievement'),
        ),
        migrations.AddField(
            model_name='citywisepmfreportachievement',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='citywisemonthlytarget',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Geography'),
        ),
        migrations.AddField(
            model_name='citywisemonthlytarget',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='citywisemonthlytarget',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='citywisemonthlytarget',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='citywisemonthlytarget',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.CityWiseMonthlyTarget'),
        ),
        migrations.AddField(
            model_name='citywisemonthlytarget',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='cdcmonthlyreport',
            name='cdc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nuprp_admin.CDC'),
        ),
        migrations.AddField(
            model_name='cdcmonthlyreport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='cdcmonthlyreport',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='cdcmonthlyreport',
            name='field_values',
            field=models.ManyToManyField(to='core.CustomFieldValue'),
        ),
        migrations.AddField(
            model_name='cdcmonthlyreport',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='cdcmonthlyreport',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Location'),
        ),
        migrations.AddField(
            model_name='cdcmonthlyreport',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.CDCMonthlyReport'),
        ),
        migrations.AddField(
            model_name='cdcmonthlyreport',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='cdcmonthlyreport',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='approvals.CDCMonthlyReport'),
        ),
        migrations.AddField(
            model_name='awarenessraisingbyscc',
            name='attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FileObject'),
        ),
        migrations.AddField(
            model_name='awarenessraisingbyscc',
            name='campaign_location_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='core.Geography'),
        ),
        migrations.AddField(
            model_name='awarenessraisingbyscc',
            name='campaign_location_ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ward', to='core.Geography'),
        ),
        migrations.AddField(
            model_name='awarenessraisingbyscc',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='awarenessraisingbyscc',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='awarenessraisingbyscc',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='awarenessraisingbyscc',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.AwarenessRaisingBySCC'),
        ),
        migrations.AddField(
            model_name='awarenessraisingbyscc',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='agreedpartnership',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='agreedpartnership',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='agreedpartnership',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='agreedpartnership',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.AgreedPartnership'),
        ),
        migrations.AddField(
            model_name='agreedpartnership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='activitiesofpartnership',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='activitiesofpartnership',
            name='entity_meta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DomainEntityMeta'),
        ),
        migrations.AddField(
            model_name='activitiesofpartnership',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ConsoleUser'),
        ),
        migrations.AddField(
            model_name='activitiesofpartnership',
            name='master_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_master', to='approvals.ActivitiesOfPartnership'),
        ),
        migrations.AddField(
            model_name='activitiesofpartnership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.CreateModel(
            name='ApprovedCDCMonthlyReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('approvals.cdcmonthlyreport',),
        ),
        migrations.CreateModel(
            name='ApprovedFieldMonitoringReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('approvals.fieldmonitoringreport',),
        ),
        migrations.CreateModel(
            name='ApprovedSCGMonthlyReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('approvals.scgmonthlyreport',),
        ),
        migrations.CreateModel(
            name='CDCMonthlyReportField',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('approvals.monthlyreportfield',),
        ),
        migrations.CreateModel(
            name='DraftFieldMonitoringReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('approvals.fieldmonitoringreport',),
        ),
        migrations.CreateModel(
            name='EligibleEducationDropOutGrantee',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('approvals.eligibleeducationgrantee',),
        ),
        migrations.CreateModel(
            name='EligibleEducationEarlyMarriageGrantee',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('approvals.eligibleeducationgrantee',),
        ),
        migrations.CreateModel(
            name='MonthlyProgress',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('approvals.citywisemonthlytarget',),
        ),
        migrations.CreateModel(
            name='MonthlyTarget',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('approvals.citywisemonthlytarget',),
        ),
        migrations.CreateModel(
            name='PendingCDCMonthlyReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('approvals.cdcmonthlyreport',),
        ),
        migrations.CreateModel(
            name='PendingSCGMonthlyReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('approvals.scgmonthlyreport',),
        ),
        migrations.CreateModel(
            name='SCGMonthlyReportField',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('approvals.monthlyreportfield',),
        ),
        migrations.CreateModel(
            name='SEFApprenticeshipGrantDisbursement',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('approvals.sefgrantdisbursement',),
        ),
        migrations.CreateModel(
            name='SEFBusinessGrantDisbursement',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('approvals.sefgrantdisbursement',),
        ),
        migrations.CreateModel(
            name='SEFEducationChildMarriageGrantDisbursement',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('approvals.sefgrantdisbursement',),
        ),
        migrations.CreateModel(
            name='SEFEducationDropoutGrantDisbursement',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('approvals.sefgrantdisbursement',),
        ),
        migrations.CreateModel(
            name='SEFNutritionGrantDisbursement',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('approvals.sefgrantdisbursement',),
        ),
        migrations.CreateModel(
            name='ShortListedEligibleApprenticeshipGrantee',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('approvals.shortlistedeligiblegrantee',),
        ),
        migrations.CreateModel(
            name='ShortListedEligibleBusinessGrantee',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('approvals.shortlistedeligiblegrantee',),
        ),
        migrations.CreateModel(
            name='ShortListedEligibleEducationDropOutGrantee',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('approvals.shortlistedeligiblegrantee',),
        ),
        migrations.CreateModel(
            name='ShortListedEligibleEducationEarlyMarriageGrantee',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('approvals.shortlistedeligiblegrantee',),
        ),
        migrations.CreateModel(
            name='SubmittedFieldMonitoringReport',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('approvals.fieldmonitoringreport',),
        ),
        migrations.AlterUniqueTogether(
            name='citywisepmfreportachievement',
            unique_together=set([('city', 'year', 'month', 'column', 'row')]),
        ),
    ]
