# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-04-13 11:19
from __future__ import unicode_literals

import blackwidow.core.mixins.modelmixin.active_inactive_model_mixin
import blackwidow.core.mixins.modelmixin.approval_process_restore_model_mixin
import blackwidow.core.mixins.modelmixin.assignment_tracked_model_mixin
import blackwidow.core.mixins.modelmixin.auditable_model_mixin
import blackwidow.core.mixins.modelmixin.child_container_model_mixin
import blackwidow.core.mixins.modelmixin.coded_model_mixin
import blackwidow.core.mixins.modelmixin.convertible_model_mixin
import blackwidow.core.mixins.modelmixin.details_view_model_mixin
import blackwidow.core.mixins.modelmixin.editable_model_mixin
import blackwidow.core.mixins.modelmixin.exportable_model_mixin
import blackwidow.core.mixins.modelmixin.list_view_model_mixin
import blackwidow.core.mixins.modelmixin.mapped_model_mixin
import blackwidow.core.mixins.modelmixin.prefetch_related_model_mixin
import blackwidow.core.mixins.modelmixin.proxy_model_mixin
import blackwidow.core.mixins.modelmixin.restorable_model_mixin
import blackwidow.core.mixins.modelmixin.restricted_model_mixin
import blackwidow.core.mixins.modelmixin.routed_model_mixin
import blackwidow.core.mixins.modelmixin.searchable_model_mixin
import blackwidow.core.mixins.modelmixin.serializable_model_mixin
import blackwidow.core.mixins.modelmixin.step_back_model_mixin
import blackwidow.core.mixins.modelmixin.versioning_model_mixin
import blackwidow.engine.mixins.modelmixin.queryset_cache_mixin
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220131_1021'),
        ('approvals', '0003_auto_20220131_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='GranteesByWPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsync_id', models.CharField(blank=True, db_index=True, max_length=55, null=True)),
                ('date_created', models.BigIntegerField(default=0, editable=False)),
                ('last_updated', models.BigIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('is_locked', models.BooleanField(default=False, editable=False)),
                ('creation_flag', models.CharField(default='Created', max_length=200)),
                ('type', models.CharField(db_index=True, default='', max_length=200)),
                ('code', models.CharField(default='', max_length=200)),
                ('deleted_level', models.SmallIntegerField(default=0)),
                ('is_version', models.BooleanField(default=False, editable=False)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('ward', models.CharField(blank=True, max_length=20, null=True)),
                ('ward_poverty_index', models.CharField(blank=True, max_length=20, null=True)),
                ('total_population', models.CharField(blank=True, max_length=20, null=True)),
                ('total_pg_registration', models.CharField(blank=True, max_length=20, null=True)),
                ('average_mpi_ward_wise', models.CharField(blank=True, max_length=20, null=True)),
                ('sef_grantees', models.CharField(blank=True, max_length=20, null=True)),
                ('nutrition_grantees', models.CharField(blank=True, max_length=20, null=True)),
                ('sif_grantees', models.CharField(blank=True, max_length=20, null=True)),
                ('crmif_grantees', models.CharField(blank=True, max_length=20, null=True)),
                ('total_grantee', models.CharField(blank=True, max_length=20, null=True)),
                ('total_family_member_benefited', models.CharField(blank=True, max_length=20, null=True)),
              
            ],
            bases=(blackwidow.core.mixins.modelmixin.list_view_model_mixin.ListViewModelMixin, blackwidow.core.mixins.modelmixin.details_view_model_mixin.DetailsViewModelMixin, blackwidow.core.mixins.modelmixin.serializable_model_mixin.SerializableModelMixin, blackwidow.core.mixins.modelmixin.routed_model_mixin.RoutedModelMixin, blackwidow.core.mixins.modelmixin.auditable_model_mixin.AuditableModelMixin, blackwidow.core.mixins.modelmixin.editable_model_mixin.EditableModelMixin, blackwidow.core.mixins.modelmixin.assignment_tracked_model_mixin.AssignmentTrackedModelMixin, blackwidow.core.mixins.modelmixin.restorable_model_mixin.RestorableModelMixin, blackwidow.core.mixins.modelmixin.proxy_model_mixin.ProxyModelMixin, blackwidow.core.mixins.modelmixin.mapped_model_mixin.MappedModelMixin, blackwidow.core.mixins.modelmixin.coded_model_mixin.CodedModelMixin, blackwidow.core.mixins.modelmixin.child_container_model_mixin.ChildContainerModelMixin, blackwidow.core.mixins.modelmixin.searchable_model_mixin.SearchableModelMixin, blackwidow.core.mixins.modelmixin.restricted_model_mixin.RestrictedModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.MutableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.ApprovableModelMixin, blackwidow.core.mixins.modelmixin.convertible_model_mixin.RejectableModelMixin, blackwidow.core.mixins.modelmixin.active_inactive_model_mixin.ActiveInactiveModelMixin, blackwidow.core.mixins.modelmixin.step_back_model_mixin.StepBackExecuteModelMixin, blackwidow.core.mixins.modelmixin.approval_process_restore_model_mixin.ApprovalRestoreModelMixin, blackwidow.engine.mixins.modelmixin.queryset_cache_mixin.QuerysetCacheMixin, blackwidow.core.mixins.modelmixin.exportable_model_mixin.ExportableModelMixin, blackwidow.core.mixins.modelmixin.prefetch_related_model_mixin.PrefetchRelatedModelMixin, blackwidow.core.mixins.modelmixin.versioning_model_mixin.VersioningModelMixin, models.Model),
        ),
    ]
